"D:\Program Files (x86)\1E\PXE Lite\bin\i386\UpdateBootImage.exe" ^
-ProviderName=LOUAPPWPS1658.rsc.humad.com ^
-SiteCode=WP1 ^
-BootImageID=WP1002B5 ^
-DistributionPoints=LOUAPPWPS1644.rsc.humad.com ^
-ManagementPoints=SMSTSLocationMPs=http://LOUAPPWPS1642.RSC.HUMAD.COM*http://LOUAPPWPS1643.RSC.HUMAD.COM*http://LOUAPPWPS1644.RSC.HUMAD.COM*http://LOUAPPWPS1645.RSC.HUMAD.COM*http://LOUAPPWPS1646.RSC.HUMAD.COM*http://LOUAPPWPS1647.RSC.HUMAD.COM*http://LOUAPPWPS1648.RSC.HUMAD.COM*http://LOUAPPWPS1649.RSC.HUMAD.COM*http://LOUAPPWPS1653.RSC.HUMAD.COM*http://LOUAPPWPS1654.RSC.HUMAD.COM*http://LOUAPPWPS1655.RSC.HUMAD.COM*http://LOUAPPWPS1656.RSC.HUMAD.COM*http://LOUAPPWPS1657.RSC.HUMAD.COM ^
-WimFileName=D:\temp\boot.wim ^
-CertPath=D:\temp\LOUAPPWPS1643-DP.pfx ^
-CertPassword=Qbe4YigsxByOIzq8Aq+V/DbyRaiuX6HKgsvlQFADoPE= ^
-CertExpiry=3650

