SELECT STM.Netbios_Name0 [WKID],
	COL.Name
FROM v_r_system STM
JOIN v_FullCollectionMembership FCM ON STM.ResourceID = FCM.ResourceID
join v_Collection COL on COL.CollectionID = FCM.CollectionID
WHERE netbios_name0 IN ('LTLADMWTS100', 'LTLADMWTS103', 'LTLATSWTS46', 'LTLCMFWTX21', 'LTLCMFWTX48', 'LTLCMFWTX92', 'LTLLOSWTS103', 'LTLSECWTS65', 'LTLSECWTX64', 'LTLSQLWTX57', 'LTLSSPWTS161', 'LTLSSPWTS77', 'LTLSSPWTS93', 'LTLSSPWTS95', 'LTLTECWTX27', 'LTLTMPW2008')
