CREATE INDEX CMN_missing_index_83_82 ON [CM_WP1].[dbo].[SoftwarePolicy] ([PkgID], [ProgramName],[ProgramCRC])
CREATE INDEX CMN_missing_index_2132_2131 ON [CM_WP1].[dbo].[AttributeMap] ([GroupKey], [IsKey])
CREATE INDEX CMN_missing_index_958_957 ON [CM_WP1].[dbo].[SoftwarePolicy] ([OfferID], [PkgID])
CREATE INDEX CMN_missing_index_4610340_4610339 ON [CM_WP1].[dbo].[System_DISC] ([ManagementAuthority]) INCLUDE ([SMS_Unique_Identifier0])
CREATE INDEX CMN_missing_index_2134_2133 ON [CM_WP1].[dbo].[AttributeMap] ([IsKey]) INCLUDE ([GroupKey])
CREATE INDEX CMN_missing_index_77_76 ON [CM_WP1].[dbo].[SoftwarePolicy] ([PkgID],[PkgCRC])
CREATE INDEX CMN_missing_index_961_960 ON [CM_WP1].[dbo].[SoftwarePolicy] ([PkgID])
CREATE INDEX CMN_missing_index_786_785 ON [CM_WP1].[dbo].[SoftwarePolicy] ([PkgID], [ProgramName], [ParentPolicyID],[OfferID])
CREATE INDEX CMN_missing_index_121_120 ON [CM_WP1].[dbo].[Group_System_Relationship] ([Group_ObjectGUID], [System_ObjectGUID]) INCLUDE ([GroupType])
CREATE INDEX CMN_missing_index_127_126 ON [CM_WP1].[dbo].[Group_System_Relationship] ([Group_ObjectGUID]) INCLUDE ([System_ObjectGUID], [GroupType])
CREATE INDEX CMN_missing_index_103_102 ON [CM_WP1].[dbo].[Group_System_Relationship] ([Group_ObjectGUID]) INCLUDE ([AgentID], [System_ObjectGUID], [GroupType], [LastRefreshTime])
CREATE INDEX CMN_missing_index_4_3 ON [CM_WP1].[dbo].[Collections_G] ([SiteID]) INCLUDE ([LimitToCollectionID])
CREATE INDEX CMN_missing_index_4489205_4489204 ON [CM_WP1].[dbo].[StatusMessages] ([SiteCode], [MachineName],[Time]) INCLUDE ([RecordID], [MessageID])
CREATE INDEX CMN_missing_index_5922826_5922825 ON [CM_WP1].[dbo].[Group_User_Relationship] ([Group_ObjectGUID]) INCLUDE ([User_ObjectGUID], [GroupType])
CREATE INDEX CMN_missing_index_2986_2985 ON [CM_WP1].[dbo].[Folders] ([Name], [IsDeleted])
CREATE INDEX CMN_missing_index_52_51 ON [CM_WP1].[dbo].[SoftwarePolicy] ([OfferID], [PkgID]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_9895_9894 ON [CM_WP1].[dbo].[TableChangeNotifications] ([Component]) INCLUDE ([Key1])
CREATE INDEX CMN_missing_index_5922822_5922821 ON [CM_WP1].[dbo].[Group_User_Relationship] ([Group_ObjectGUID], [User_ObjectGUID]) INCLUDE ([GroupType])
CREATE INDEX CMN_missing_index_4495271_4495270 ON [CM_WP1].[dbo].[Update_ComplianceStatus] ([Status]) INCLUDE ([CI_ID], [MachineID], [EnforcementSource], [LastEnforcementMessageID])
CREATE INDEX CMN_missing_index_4495793_4495792 ON [CM_WP1].[dbo].[Update_ComplianceStatus] ([EnforcementSource],[LastEnforcementMessageID], [LastEnforcementMessageTime]) INCLUDE ([CI_ID], [MachineID])
CREATE INDEX CMN_missing_index_909_908 ON [CM_WP1].[dbo].[PolicyAssignment] ([PolicyAssignmentID])
CREATE INDEX CMN_missing_index_123_122 ON [CM_WP1].[dbo].[Group_Group_Relationship] ([ParentGroup_ObjectGUID])
CREATE INDEX CMN_missing_index_4495453_4495452 ON [CM_WP1].[dbo].[Update_ComplianceStatus] ([MachineID],[LastStatusCheckTime], [LastEnforcementMessageTime]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_4610707_4610706 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey]) INCLUDE ([Netbios_Name0], [User_Name0], [Obsolete0])
CREATE INDEX CMN_missing_index_5922819_5922818 ON [CM_WP1].[dbo].[Group_User_Relationship] ([Group_ObjectGUID]) INCLUDE ([AgentID], [User_ObjectGUID], [GroupType], [LastRefreshTime])
CREATE INDEX CMN_missing_index_19162_19161 ON [CM_WP1].[dbo].[FolderMembers] ([ContainerNodeID], [IsDeleted])
CREATE INDEX CMN_missing_index_12677_12676 ON [CM_WP1].[dbo].[TableChangeNotifications] ([Component])
CREATE INDEX CMN_missing_index_1274161_1274160 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([CIType_ID]) INCLUDE ([CI_ID], [ModelId], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_92_91 ON [CM_WP1].[dbo].[DepPolicyAssignment] ([DepPADBID]) INCLUDE ([PADBID], [IsTombstoned])
CREATE INDEX CMN_missing_index_4481323_4481322 ON [CM_WP1].[dbo].[ResOfferCollMap] ([OfferID]) INCLUDE ([MachineID], [CollectionID])
CREATE INDEX CMN_missing_index_47203_47202 ON [CM_WP1].[dbo].[FolderMembers] ([IsDeleted]) INCLUDE ([ContainerNodeID])
CREATE INDEX CMN_missing_index_4495422_4495421 ON [CM_WP1].[dbo].[Update_ComplianceStatus] ([MachineID]) INCLUDE ([CI_ID], [Status], [LastStatusCheckTime], [LastEnforcementMessageID], [rowversion])
CREATE INDEX CMN_missing_index_6405480_6405479 ON [CM_WP1].[dbo].[SHORTCUT_FILE_HIST] ([MachineID], [Name00]) INCLUDE ([InstanceKey])
CREATE INDEX CMN_missing_index_4519608_4519607 ON [CM_WP1].[dbo].[SoftwareInventory] ([ProductId]) INCLUDE ([ClientId])
CREATE INDEX CMN_missing_index_61_60 ON [CM_WP1].[dbo].[SoftwarePolicy] ([OfferID])
CREATE INDEX CMN_missing_index_4557389_4557388 ON [CM_WP1].[dbo].[StatusMessages] ([DeleteTime]) INCLUDE ([RecordID])
CREATE INDEX CMN_missing_index_6485229_6485228 ON [CM_WP1].[dbo].[Add_Remove_Programs_HIST] ([MachineID], [ProdID00]) INCLUDE ([InstanceKey])
CREATE INDEX CMN_missing_index_4612096_4612095 ON [CM_WP1].[dbo].[System_DISC] ([Name0], [Client0], [Obsolete0], [Decommissioned0],[ItemKey])
CREATE INDEX CMN_missing_index_4503121_4503120 ON [CM_WP1].[dbo].[RBAC_InstancePermissions] ([ObjectTypeID]) INCLUDE ([AdminID], [ObjectKey], [GrantedOperations])
CREATE INDEX CMN_missing_index_59_58 ON [CM_WP1].[dbo].[SoftwarePolicy] ([ParentPolicyID],[OfferID]) INCLUDE ([PolicyID], [PkgID], [ProgramName])
CREATE INDEX CMN_missing_index_2580_2579 ON [CM_WP1].[dbo].[DiscScope_ImmediateGroup] ([Group_ObjectGUID])
CREATE INDEX CMN_missing_index_10685_10684 ON [CM_WP1].[dbo].[ActiveDirectoryObjectInfo] ([CName])
CREATE INDEX CMN_missing_index_14967_14966 ON [CM_WP1].[dbo].[DeploymentSummary] ([OfferID])
CREATE INDEX CMN_missing_index_4482007_4482006 ON [CM_WP1].[dbo].[ResPolicyMap] ([IsTombstoned]) INCLUDE ([MachineID], [PADBID])
CREATE INDEX CMN_missing_index_2610344_2610343 ON [ReportServer].[dbo].[ExecutionLogStorage] ([ReportAction]) INCLUDE ([ReportID], [TimeStart])
CREATE INDEX CMN_missing_index_4610344_4610343 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[Object_GUID0]) INCLUDE ([ItemKey], [Distinguished_Name0], [SID0])
CREATE INDEX CMN_missing_index_2681353_2681352 ON [CM_WP1].[dbo].[Flat_Group_User_Relationship_NS] ([Group_ObjectGUID], [SiteCode]) INCLUDE ([User_ObjectGUID])
CREATE INDEX CMN_missing_index_94_93 ON [CM_WP1].[dbo].[DepPolicyAssignment] ([IsTombstoned]) INCLUDE ([PADBID], [DepPADBID])
CREATE INDEX CMN_missing_index_10176_10175 ON [CM_WP1].[dbo].[CollectionNotifications] ([TableName],[RecordID], [MachineID])
CREATE INDEX CMN_missing_index_4618924_4618923 ON [CM_WP1].[dbo].[System_DISC] ([Client_Type0],[AgentEdition0]) INCLUDE ([ItemKey])
CREATE INDEX CMN_missing_index_2864_2863 ON [CM_WP1].[dbo].[ActiveDirectoryObjectInfo] ([SiteCode], [LastRefreshTime]) INCLUDE ([ObjectGUID])
CREATE INDEX CMN_missing_index_2681355_2681354 ON [CM_WP1].[dbo].[Flat_Group_User_Relationship_NS] ([SiteCode]) INCLUDE ([Group_ObjectGUID], [User_ObjectGUID])
CREATE INDEX CMN_missing_index_5923980_5923979 ON [CM_WP1].[dbo].[Flat_Group_User_Relationship_Path] ([ParentGroup]) INCLUDE ([ChildUser], [IsSecureRelationship])
CREATE INDEX CMN_missing_index_4495610_4495609 ON [CM_WP1].[dbo].[User_DISC] ([Object_GUID0]) INCLUDE ([ItemKey], [SID0], [Distinguished_Name0])
CREATE INDEX CMN_missing_index_4618926_4618925 ON [CM_WP1].[dbo].[System_DISC] ([Client_Type0]) INCLUDE ([ItemKey])
CREATE INDEX CMN_missing_index_67_66 ON [CM_WP1].[dbo].[PkgPrograms_G] ([DependentProgram]) INCLUDE ([PkgID], [Name])
CREATE INDEX CMN_missing_index_5927222_5927221 ON [CM_WP1].[dbo].[MachineIdGroupXRef] ([ArchitectureKey],[MachineID]) INCLUDE ([GUID])
CREATE INDEX CMN_missing_index_4474861_4474860 ON [CM_WP1].[dbo].[PkgServers_L] ([NALPath])
CREATE INDEX CMN_missing_index_441_440 ON [CM_WP1].[dbo].[FolderMembers] ([ContainerNodeID], [IsDeleted]) INCLUDE ([InstanceKey])
CREATE INDEX CMN_missing_index_10412_10411 ON [CM_WP1].[dbo].[TableChangeNotifications] ([Component]) INCLUDE ([TargetTriggerTime])
CREATE INDEX CMN_missing_index_10197_10196 ON [CM_WP1].[dbo].[CollectionNotifications] ([Group_ObjectGUID],[RecordID]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_4503127_4503126 ON [CM_WP1].[dbo].[ResOfferCollMap] ([OfferID]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_78246_78245 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([IsUserCI]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_2862_2861 ON [CM_WP1].[dbo].[Flat_Group_Group_Relationship] ([ChildGroup_ObjectGUID]) INCLUDE ([ParentGroup_ObjectGUID])
CREATE INDEX CMN_missing_index_5938619_5938618 ON [CM_WP1].[dbo].[Flat_Group_User_Relationship] ([Group_ObjectGUID]) INCLUDE ([User_ObjectGUID])
CREATE INDEX CMN_missing_index_75_74 ON [CM_WP1].[dbo].[ActiveDirectoryObjectInfo] ([Name])
CREATE INDEX CMN_missing_index_443_442 ON [CM_WP1].[dbo].[Folders] ([Name], [ObjectType], [IsDeleted])
CREATE INDEX CMN_missing_index_1607375_1607374 ON [CM_WP1].[dbo].[BGB_ResStatus] ([ServerID]) INCLUDE ([ResourceID], [OnlineStatus])
CREATE INDEX CMN_missing_index_5910138_5910137 ON [CM_WP1].[dbo].[DiscItemAgents] ([AgentID]) INCLUDE ([ItemKey], [AgentTime])
CREATE INDEX CMN_missing_index_10933_10932 ON [CM_WP1].[dbo].[Flat_Group_System_Relationship] ([Group_ObjectGUID], [SiteCode]) INCLUDE ([System_ObjectGUID])
CREATE INDEX CMN_missing_index_4621419_4621418 ON [CM_WP1].[dbo].[INSTALLED_EXECUTABLE_DATA] ([Description00]) INCLUDE ([BinFileVersion00], [BinProductVersion00], [ExecutableName00], [FilePropertiesHash00], [FilePropertiesHashEx00], [FileSize00], [FileVersion00], [HasPatchAdded00], [InstalledFilePath00], [IsSystemFile00], [IsVitalFile00], [Language00], [Product00], [ProductCode00], [ProductVersion00], [Publisher00], [MachineID], [InstanceKey], [TimeKey], [RevisionID], [AgentID])
CREATE INDEX CMN_missing_index_4613534_4613533 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([Client0], [Client_Type0], [Obsolete0])
CREATE INDEX CMN_missing_index_78244_78243 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([IsHidden], [IsTombstoned],[CIType_ID]) INCLUDE ([CI_ID], [CI_UniqueID], [ModelId], [CIVersion], [DateCreated], [DateLastModified], [LastModifiedBy], [CreatedBy], [PermittedUses], [IsBundle], [IsUserDefined], [IsEnabled], [IsExpired], [IsLatest], [SourceSite], [ApplicabilityCondition], [ConfigurationFlags], [IsUserCI], [SEDOComponentID])
CREATE INDEX CMN_missing_index_948_947 ON [CM_WP1].[dbo].[SoftwarePolicy] ([OfferID]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_800035_800034 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([CIType_ID], [IsTombstoned]) INCLUDE ([ModelId])
CREATE INDEX CMN_missing_index_10781_10780 ON [CM_WP1].[dbo].[ActiveDirectoryObjectInfo] ([CName]) INCLUDE ([ObjectGUID], [SiteCode], [LastRefreshTime])
CREATE INDEX CMN_missing_index_950_949 ON [CM_WP1].[dbo].[SoftwarePolicy] ([OfferID], [ParentPolicyID]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_5910303_5910302 ON [CM_WP1].[dbo].[Flat_Group_User_Relationship] ([Group_ObjectGUID], [SiteCode]) INCLUDE ([User_ObjectGUID])
CREATE INDEX CMN_missing_index_800037_800036 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([IsTombstoned],[CIType_ID]) INCLUDE ([ModelId])
CREATE INDEX CMN_missing_index_930_929 ON [CM_WP1].[dbo].[PolicyAssignment] ([PolicyAssignmentID]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_952_951 ON [CM_WP1].[dbo].[SoftwarePolicy] ([ParentPolicyID]) INCLUDE ([PADBID], [OfferID])
CREATE INDEX CMN_missing_index_3302_3301 ON [msdb].[dbo].[sysjobhistory] ([step_id]) INCLUDE ([instance_id], [job_id], [run_date], [run_time])
CREATE INDEX CMN_missing_index_22_21 ON [CM_WP1].[dbo].[ContentDistributionNotification] ([DPID]) INCLUDE ([DistributionID])
CREATE INDEX CMN_missing_index_2_1 ON [msdb].[dbo].[sysjobhistory] ([job_id], [step_id], [run_date], [run_time])
CREATE INDEX CMN_missing_index_5958354_5958353 ON [CM_WP1].[dbo].[INSTALLED_SOFTWARE_DATA] ([ProductName00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_61550_61549 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([CIType_ID], [IsTombstoned]) INCLUDE ([CI_ID], [CI_UniqueID])
CREATE INDEX CMN_missing_index_32171_32170 ON [CM_WP1].[dbo].[Flat_Group_System_Relationship_Path] ([ParentGroup]) INCLUDE ([ChildSystem], [IsSecureRelationship])
CREATE INDEX CMN_missing_index_102315_102314 ON [CM_WP1].[dbo].[SEDO_LockState] ([LockID]) INCLUDE ([ID])
CREATE INDEX CMN_missing_index_18249_18248 ON [CM_WP1].[dbo].[CollectionMemberCounts] ([SiteNumber]) INCLUDE ([CollectionID], [AssignedCount], [UnassignedCount])
CREATE INDEX CMN_missing_index_4639964_4639963 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Resource_Domain_OR_Workgr0], [Client0])
CREATE INDEX CMN_missing_index_622_621 ON [ReportServer].[dbo].[Catalog] ([Type]) INCLUDE ([ModifiedDate])
CREATE INDEX CMN_missing_index_4621398_4621397 ON [CM_WP1].[dbo].[System_DISC] ([Name0], [Decommissioned0],[ItemKey])
CREATE INDEX CMN_missing_index_4636569_4636568 ON [CM_WP1].[dbo].[TaskExecutionStatus] ([ActionName]) INCLUDE ([OfferID], [ItemKey], [ExecutionTime], [GroupName], [LastStatus], [ExitCode], [ActionOutput])
CREATE INDEX CMN_missing_index_102313_102312 ON [CM_WP1].[dbo].[SEDO_LockableObjectComponents] ([ObjectID]) INCLUDE ([ComponentID])
CREATE INDEX CMN_missing_index_5923984_5923983 ON [CM_WP1].[dbo].[Flat_Group_User_Relationship] ([SiteCode]) INCLUDE ([Group_ObjectGUID], [User_ObjectGUID])
CREATE INDEX CMN_missing_index_9942_9941 ON [CM_WP1].[dbo].[Collections_G] ([Schedule]) INCLUDE ([CollectionID], [Flags])
CREATE INDEX CMN_missing_index_4597911_4597910 ON [CM_WP1].[dbo].[Add_Remove_Programs_DATA] ([MachineID],[Publisher00])
CREATE INDEX CMN_missing_index_35_34 ON [CM_WP1].[dbo].[Library_ImportedObjects] ([ObjectTypeID], [ObjectKey]) INCLUDE ([ImportID])
CREATE INDEX CMN_missing_index_4474868_4474867 ON [CM_WP1].[dbo].[PkgServers_G] ([NALPath], [SiteCode]) INCLUDE ([PkgID])
CREATE INDEX CMN_missing_index_37_36 ON [CM_WP1].[dbo].[Library_ImportedObjects] ([ObjectTypeID]) INCLUDE ([ImportID], [ObjectKey])
CREATE INDEX CMN_missing_index_43_42 ON [CM_WP1].[dbo].[SR_ClientMessageStats] ([LastResyncIssuedTime]) INCLUDE ([MachineID], [LastResyncClientCompletedTime])
CREATE INDEX CMN_missing_index_61552_61551 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([IsTombstoned]) INCLUDE ([CI_ID], [CI_UniqueID], [CIType_ID])
CREATE INDEX CMN_missing_index_926_925 ON [CM_WP1].[dbo].[PolicyAssignment] ([IsTombstoned]) INCLUDE ([PADBID], [PolicyAssignmentID])
CREATE INDEX CMN_missing_index_3600029_3600028 ON [CM_WP1].[dbo].[Add_Remove_Programs_64_DATA] ([DisplayName00]) INCLUDE ([MachineID], [Version00])
CREATE INDEX CMN_missing_index_2855_2854 ON [CM_WP1].[dbo].[Flat_Group_System_Relationship] ([SiteCode]) INCLUDE ([Group_ObjectGUID], [System_ObjectGUID])
CREATE INDEX CMN_missing_index_3304_3303 ON [msdb].[dbo].[sysjobhistory] ([step_id]) INCLUDE ([instance_id], [job_id], [run_status], [run_date], [run_time], [run_duration])
CREATE INDEX CMN_missing_index_445_444 ON [CM_WP1].[dbo].[FolderMembers] ([IsDeleted]) INCLUDE ([ContainerNodeID], [InstanceKey])
CREATE INDEX CMN_missing_index_361131_361130 ON [CM_WP1].[dbo].[DepPolicyAssignment] ([DepPADBID], [IsTombstoned],[PADBID])
CREATE INDEX CMN_missing_index_4969973_4969972 ON [CM_WP1].[dbo].[StatusMessages] ([Component],[Time]) INCLUDE ([RecordID], [MachineName], [ProcessID], [ThreadID])
CREATE INDEX CMN_missing_index_4616034_4616033 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey], [Operating_System_Name_and0]) INCLUDE ([Obsolete0])
CREATE INDEX CMN_missing_index_2670024_2670023 ON [CM_WP1].[dbo].[ContentDistributionMessages] ([DPID]) INCLUDE ([DistributionID])
CREATE INDEX CMN_missing_index_3600025_3600024 ON [CM_WP1].[dbo].[Add_Remove_Programs_64_DATA] ([DisplayName00]) INCLUDE ([MachineID], [Version00])
CREATE INDEX CMN_missing_index_7356_7355 ON [CM_WP1].[dbo].[Folders] ([Name], [ObjectType], [IsDeleted]) INCLUDE ([ContainerNodeID])
CREATE INDEX CMN_missing_index_2695842_2695841 ON [CM_WP1].[dbo].[CI_ConfigurationItemsOptionalRelations] ([RelationType]) INCLUDE ([FromCI_ID], [ToCI_ID], [IsVersionSpecific])
CREATE INDEX CMN_missing_index_17979_17978 ON [CM_WP1].[dbo].[SoftwarePolicy] ([OfferID]) INCLUDE ([PolicyID])
CREATE INDEX CMN_missing_index_2684565_2684564 ON [CM_WP1].[dbo].[Logical_Disk_DATA] ([FreeSpace00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_4699986_4699985 ON [CM_WP1].[dbo].[System_DISC] ([Resource_Domain_OR_Workgr0], [Client0], [Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0])
CREATE INDEX CMN_missing_index_4596139_4596138 ON [CM_WP1].[dbo].[User_DISC] ([User_Name0]) INCLUDE ([Full_User_Name0])
CREATE INDEX CMN_missing_index_4538420_4538419 ON [CM_WP1].[dbo].[ResPolicyMap] ([IsTombstoned],[LastUpdateTime]) INCLUDE ([MachineID], [PADBID])
CREATE INDEX CMN_missing_index_788703_788702 ON [CM_WP1].[dbo].[Flat_Group_Group_Relationship_Path] ([ParentGroup]) INCLUDE ([ChildGroup], [IsSecureRelationship])
CREATE INDEX CMN_missing_index_55945_55944 ON [CM_WP1].[dbo].[SMSPackages_G] ([Name]) INCLUDE ([PkgID], [Manufacturer], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_4643468_4643467 ON [CM_WP1].[dbo].[System_DISC] ([Resource_Domain_OR_Workgr0], [Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Client0])
CREATE INDEX CMN_missing_index_4700084_4700083 ON [CM_WP1].[dbo].[TaskExecutionStatus] ([ActionTypeName]) INCLUDE ([OfferID], [ItemKey], [ExecutionTime])
CREATE INDEX CMN_missing_index_4665566_4665565 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey], [Operating_System_Name_and0]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Resource_Domain_OR_Workgr0], [Client0])
CREATE INDEX CMN_missing_index_5789787_5789786 ON [CM_WP1].[dbo].[QUICK_FIX_ENGINEERING_HIST] ([TimeKey]) INCLUDE ([MachineID], [InstanceKey], [RevisionID])
CREATE INDEX CMN_missing_index_6149903_6149902 ON [CM_WP1].[dbo].[PATH_CUSTOM_HIST] ([TimeKey]) INCLUDE ([MachineID], [InstanceKey], [RevisionID])
CREATE INDEX CMN_missing_index_823633_823632 ON [CM_WP1].[dbo].[Add_Remove_Programs_64_DATA] ([Publisher00]) INCLUDE ([MachineID], [DisplayName00], [Version00])
CREATE INDEX CMN_missing_index_444483_444482 ON [CM_WP1].[dbo].[CI_CurrentErrorDetails] ([CI_ID]) INCLUDE ([RecordID])
CREATE INDEX CMN_missing_index_2708477_2708476 ON [CM_WP1].[dbo].[SCCM_Audit] ([ChangeTime]) INCLUDE ([ID])
CREATE INDEX CMN_missing_index_1868052_1868051 ON [CM_WP1].[dbo].[Add_Remove_Programs_64_DATA] ([Version00]) INCLUDE ([MachineID], [DisplayName00], [Publisher00])
CREATE INDEX CMN_missing_index_79245_79244 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([CIType_ID]) INCLUDE ([CI_ID], [ModelId], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_11271_11270 ON [CM_WP1].[dbo].[DeploymentSummary] ([AssignmentID]) INCLUDE ([SummarizationTime])
CREATE INDEX CMN_missing_index_1622025_1622024 ON [CM_WP1].[dbo].[BGB_ResStatus] ([ServerID]) INCLUDE ([OnlineStatus])
CREATE INDEX CMN_missing_index_4722014_4722013 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([Name0])
CREATE INDEX CMN_missing_index_4781281_4781280 ON [CM_WP1].[dbo].[ResOfferCollMap] ([CollectionID]) INCLUDE ([MachineID], [OfferID])
CREATE INDEX CMN_missing_index_6616_6615 ON [msdb].[dbo].[backupfile] ([file_type]) INCLUDE ([backup_set_id], [file_number])
CREATE INDEX CMN_missing_index_2715552_2715551 ON [CM_WP1].[dbo].[System_DATA] ([Name0]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_6620_6619 ON [msdb].[dbo].[backupfile] ([file_type]) INCLUDE ([backup_set_id], [file_number])
CREATE INDEX CMN_missing_index_4717799_4717798 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0], [Is_Virtual_Machine0],[ItemKey], [Resource_Domain_OR_Workgr0]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Operating_System_Name_and0])
CREATE INDEX CMN_missing_index_4502972_4502971 ON [CM_WP1].[dbo].[User_DISC] ([User_Name0]) INCLUDE ([Full_User_Name0], [Mail0])
CREATE INDEX CMN_missing_index_4496576_4496575 ON [CM_WP1].[dbo].[UserMachineRelation] ([RelationActive]) INCLUDE ([RelationshipResourceID])
CREATE INDEX CMN_missing_index_4729751_4729750 ON [CM_WP1].[dbo].[ResPolicyMap] ([MachineID], [TargetSourceID], [IsTombstoned]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_3566107_3566106 ON [CM_WP1].[dbo].[Add_Remove_Programs_64_DATA] ([DisplayName00]) INCLUDE ([Publisher00], [Version00])
CREATE INDEX CMN_missing_index_4713714_4713713 ON [CM_WP1].[dbo].[System_DISC] ([Obsolete0], [Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Resource_Domain_OR_Workgr0], [Client0])
CREATE INDEX CMN_missing_index_6082452_6082451 ON [CM_WP1].[dbo].[ROOT_CA_HIST] ([TimeKey]) INCLUDE ([MachineID], [InstanceKey], [RevisionID])
CREATE INDEX CMN_missing_index_66428_66427 ON [CM_WP1].[dbo].[SEDO_LockState] ([LockID])
CREATE INDEX CMN_missing_index_6140236_6140235 ON [CM_WP1].[dbo].[Network_DATA] ([IPAddress00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_6614_6613 ON [msdb].[dbo].[backupset] ([type]) INCLUDE ([backup_set_id], [backup_finish_date], [database_name])
CREATE INDEX CMN_missing_index_31_30 ON [CM_WP1].[dbo].[CollectionOfferList] ([OfferID]) INCLUDE ([CollectionID])
CREATE INDEX CMN_missing_index_33_32 ON [CM_WP1].[dbo].[CollectionOfferListAC] ([OfferID]) INCLUDE ([CollectionID])
CREATE INDEX CMN_missing_index_4720652_4720651 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey], [Resource_Domain_OR_Workgr0], [Is_Virtual_Machine0]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Operating_System_Name_and0])
CREATE INDEX CMN_missing_index_64070_64069 ON [CM_WP1].[dbo].[Folders] ([ParentContainerNodeID])
CREATE INDEX CMN_missing_index_2735030_2735029 ON [CM_WP1].[dbo].[InternetExplorer64_DATA] ([svcVersion00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_6618_6617 ON [msdb].[dbo].[backupset] ([type]) INCLUDE ([backup_set_id], [backup_finish_date], [database_name])
CREATE INDEX CMN_missing_index_4729753_4729752 ON [CM_WP1].[dbo].[ResPolicyMap] ([TargetSourceID], [IsTombstoned]) INCLUDE ([MachineID], [PADBID])
CREATE INDEX CMN_missing_index_4713699_4713698 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Operating_System_Name_and0], [Resource_Domain_OR_Workgr0])
CREATE INDEX CMN_missing_index_4154059_4154058 ON [ReportServer].[dbo].[PolicyUserRole] ([PolicyID]) INCLUDE ([RoleID], [UserID])
CREATE INDEX CMN_missing_index_1036873_1036872 ON [CM_WP1].[dbo].[LU_SoftwareList] ([SourceSite],[LastUpdated])
CREATE INDEX CMN_missing_index_4694883_4694882 ON [CM_WP1].[dbo].[System_DISC] ([Resource_Domain_OR_Workgr0], [Client0], [Obsolete0], [Active0], [Decommissioned0],[ItemKey], [Creation_Date0]) INCLUDE ([SMS_Unique_Identifier0])
CREATE INDEX CMN_missing_index_61623_61622 ON [CM_WP1].[dbo].[SoftwarePolicy] ([OfferID],[OfferCRC])
CREATE INDEX CMN_missing_index_78149_78148 ON [CM_WP1].[dbo].[FolderMembers] ([ContainerNodeID]) INCLUDE ([MemberID])
CREATE INDEX CMN_missing_index_3788532_3788531 ON [CM_WP1].[dbo].[Add_Remove_Programs_64_DATA] ([Publisher00]) INCLUDE ([MachineID], [InstanceKey], [RevisionID], [AgentID], [TimeKey], [ProdID00], [DisplayName00], [InstallDate00], [Version00])
CREATE INDEX CMN_missing_index_4719900_4719899 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([SMS_Unique_Identifier0], [Name0], [Resource_Domain_OR_Workgr0], [Client0])
CREATE INDEX CMN_missing_index_234794_234793 ON [CM_WP1].[dbo].[Library_ImportedObjects] ([ObjectKey],[ObjectTypeID]) INCLUDE ([ImportID])
CREATE INDEX CMN_missing_index_102311_102310 ON [CM_WP1].[dbo].[Library_ImportedObjects] ([ObjectTypeID]) INCLUDE ([ImportID], [ObjectKey])
CREATE INDEX CMN_missing_index_4642453_4642452 ON [CM_WP1].[dbo].[PkgServers_L] ([NALPath],[Action])
CREATE INDEX CMN_missing_index_4678595_4678594 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey], [User_Name0]) INCLUDE ([Netbios_Name0], [Obsolete0])
CREATE INDEX CMN_missing_index_4736099_4736098 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey], [Client_Version0]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Resource_Domain_OR_Workgr0], [Client0])
CREATE INDEX CMN_missing_index_3568228_3568227 ON [CM_WP1].[dbo].[Add_Remove_Programs_64_DATA] ([DisplayName00]) INCLUDE ([InstallDate00], [Publisher00], [Version00])
CREATE INDEX CMN_missing_index_4722279_4722278 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey], [Resource_Domain_OR_Workgr0], [Is_Virtual_Machine0]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0])
CREATE INDEX CMN_missing_index_4724319_4724318 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0], [Is_Virtual_Machine0],[ItemKey], [Resource_Domain_OR_Workgr0]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0])
CREATE INDEX CMN_missing_index_2769524_2769523 ON [CM_WP1].[dbo].[Netcard_DATA] ([MACAddress00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_128505_128504 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([IsTombstoned]) INCLUDE ([ConfigurationFlags])
CREATE INDEX CMN_missing_index_2817668_2817667 ON [CM_WP1].[dbo].[Update_DetectionStatus] ([StatusTime]) INCLUDE ([CI_UniqueID], [MachineID])
CREATE INDEX CMN_missing_index_1036875_1036874 ON [CM_WP1].[dbo].[LU_SoftwareHash] ([SourceSite],[LastUpdated])
CREATE INDEX CMN_missing_index_5978387_5978386 ON [CM_WP1].[dbo].[Operating_System_DATA] ([Caption00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_4731139_4731138 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey], [Resource_Domain_OR_Workgr0], [Is_Virtual_Machine0]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Netbios_Name0], [Name0], [Operating_System_Name_and0])
CREATE INDEX CMN_missing_index_4713736_4713735 ON [CM_WP1].[dbo].[System_DISC] ([Client_Version0], [Decommissioned0],[ItemKey])
CREATE INDEX CMN_missing_index_102309_102308 ON [CM_WP1].[dbo].[CI_CIDocuments] ([Document_ID]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_4713730_4713729 ON [CM_WP1].[dbo].[System_DISC] ([Client_Version0], [Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Resource_Domain_OR_Workgr0], [Client0])
CREATE INDEX CMN_missing_index_4713726_4713725 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Resource_Domain_OR_Workgr0], [Client0], [Creation_Date0])
CREATE INDEX CMN_missing_index_6509415_6509414 ON [CM_WP1].[dbo].[Collection_Rules] ([QueryKey])
CREATE INDEX CMN_missing_index_4622443_4622442 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0], [Is_Virtual_Machine0],[ItemKey], [Resource_Domain_OR_Workgr0]) INCLUDE ([Operating_System_Name_and0])
CREATE INDEX CMN_missing_index_4651583_4651582 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey], [Operating_System_Name_and0]) INCLUDE ([Netbios_Name0], [User_Name0], [Obsolete0], [Is_Virtual_Machine0])
CREATE INDEX CMN_missing_index_4725702_4725701 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Operating_System_Name_and0], [Resource_Domain_OR_Workgr0], [Client0])
CREATE INDEX CMN_missing_index_965031_965030 ON [CM_WP1].[dbo].[BGB_ResTask] ([TaskID]) INCLUDE ([ResourceID])
CREATE INDEX CMN_missing_index_5975078_5975077 ON [CM_WP1].[dbo].[Computer_System_DATA] ([SystemType00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_5912406_5912405 ON [CM_WP1].[dbo].[ClientDeploymentState] ([BaselineCookie]) INCLUDE ([RecordID], [SMSID], [InstalledLangs])
CREATE INDEX CMN_missing_index_4605421_4605420 ON [CM_WP1].[dbo].[CollectionMembers] ([SiteID], [ArchitectureKey]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_4598232_4598231 ON [CM_WP1].[dbo].[User_DISC] ([User_Name0]) INCLUDE ([ItemKey], [DiscArchKey], [Unique_User_Name0], [Windows_NT_Domain0], [Name0])
CREATE INDEX CMN_missing_index_4621363_4621362 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([Netbios_Name0], [User_Name0], [Client_Type0], [User_Domain0])
CREATE INDEX CMN_missing_index_41642_41641 ON [CM_WP1].[dbo].[User_Group_DISC] ([Usergroup_Name0])
CREATE INDEX CMN_missing_index_4623124_4623123 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([Netbios_Name0], [Operating_System_Name_and0])
CREATE INDEX CMN_missing_index_4579894_4579893 ON [CM_WP1].[dbo].[User_DISC] ([Full_Domain_Name0]) INCLUDE ([ItemKey], [DiscArchKey], [Unique_User_Name0], [Windows_NT_Domain0], [Name0])
CREATE INDEX CMN_missing_index_444466_444465 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([IsTombstoned], [IsExpired], [SourceSite],[CIType_ID]) INCLUDE ([CI_ID], [DateCreated], [DateLastModified], [rowversion])
CREATE INDEX CMN_missing_index_78338_78337 ON [CM_WP1].[dbo].[Folders] ([ObjectType]) INCLUDE ([ContainerNodeID])
CREATE INDEX CMN_missing_index_4695266_4695265 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([SMS_Unique_Identifier0], [Creation_Date0])
CREATE INDEX CMN_missing_index_5295047_5295046 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([Name0], [Client0], [Obsolete0], [Active0], [SMBIOS_GUID0])
CREATE INDEX CMN_missing_index_128418_128417 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([CIType_ID], [IsTombstoned]) INCLUDE ([IsEnabled])
CREATE INDEX CMN_missing_index_78157_78156 ON [CM_WP1].[dbo].[FolderMembers] ([ContainerNodeID], [IsDeleted]) INCLUDE ([MemberID])
CREATE INDEX CMN_missing_index_3068710_3068709 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([IsHidden], [IsTombstoned],[CIType_ID]) INCLUDE ([CI_ID], [ModelId])
CREATE INDEX CMN_missing_index_4736081_4736080 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Resource_Domain_OR_Workgr0])
CREATE INDEX CMN_missing_index_4662810_4662809 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey], [Obsolete0]) INCLUDE ([Name0], [Resource_Domain_OR_Workgr0])
CREATE INDEX CMN_missing_index_4733040_4733039 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Resource_Domain_OR_Workgr0], [Client0], [Client_Type0], [AgentEdition0])
CREATE INDEX CMN_missing_index_4927414_4927413 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([User_Name0])
CREATE INDEX CMN_missing_index_4736000_4735999 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey], [Client0]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Resource_Domain_OR_Workgr0])
CREATE INDEX CMN_missing_index_4709542_4709541 ON [CM_WP1].[dbo].[User_DISC] ([Windows_NT_Domain0]) INCLUDE ([ItemKey], [DiscArchKey], [Unique_User_Name0], [Name0])
CREATE INDEX CMN_missing_index_2760612_2760611 ON [CM_WP1].[dbo].[Logical_Disk_DATA] ([DeviceID00],[FreeSpace00]) INCLUDE ([Size00], [MachineID])
CREATE INDEX CMN_missing_index_4746194_4746193 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Resource_Domain_OR_Workgr0], [Client0], [Client_Type0], [AgentEdition0], [EAS_DeviceID])
CREATE INDEX CMN_missing_index_11046_11045 ON [ReportServer].[dbo].[Catalog] ([Type]) INCLUDE ([ParentID])
CREATE INDEX CMN_missing_index_4622445_4622444 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0], [Is_Virtual_Machine0],[ItemKey], [Resource_Domain_OR_Workgr0]) INCLUDE ([Netbios_Name0], [Operating_System_Name_and0], [User_Name0])
CREATE INDEX CMN_missing_index_4584175_4584174 ON [CM_WP1].[dbo].[User_DISC] ([Full_Domain_Name0]) INCLUDE ([ItemKey], [DiscArchKey], [Unique_User_Name0], [Windows_NT_Domain0], [Name0])
CREATE INDEX CMN_missing_index_3229211_3229210 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([IsTombstoned]) INCLUDE ([CI_ID], [CIType_ID], [IsExpired], [IsLatest], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_3229213_3229212 ON [CM_WP1].[dbo].[CI_ContentPackages] ([PkgID],[ContentVersion])
CREATE INDEX CMN_missing_index_574915_574914 ON [CM_WP1].[dbo].[PfxAssignment_Notify] ([CollectionID], [Flag])
CREATE INDEX CMN_missing_index_1713872_1713871 ON [CM_WP1].[dbo].[BGB_ResStatus] ([ServerID],[ResourceID]) INCLUDE ([OnlineStatus])
CREATE INDEX CMN_missing_index_11048_11047 ON [ReportServer].[dbo].[Catalog] ([Type]) INCLUDE ([ItemID], [Path], [ParentID], [Description], [Hidden], [CreationDate])
CREATE INDEX CMN_missing_index_4622441_4622440 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0], [Is_Virtual_Machine0],[ItemKey], [Resource_Domain_OR_Workgr0]) INCLUDE ([Netbios_Name0], [Operating_System_Name_and0], [AD_Site_Name0], [User_Name0])
CREATE INDEX CMN_missing_index_4709364_4709363 ON [CM_WP1].[dbo].[StatusMessageAttributes] ([AttributeID], [AttributeValue]) INCLUDE ([RecordID], [AttributeTime])
CREATE INDEX CMN_missing_index_4481280_4481279 ON [CM_WP1].[dbo].[PkgServers_L] ([NALPath]) INCLUDE ([Action])
CREATE INDEX CMN_missing_index_856259_856258 ON [CM_WP1].[SCCM_Ext].[INSTALLED_EXECUTABLE_DATA_DD] ([DelDate]) INCLUDE ([rowversion])
CREATE INDEX CMN_missing_index_237446_237445 ON [CM_WP1].[dbo].[DeploymentSummary] ([Type]) INCLUDE ([SiteNumber], [CollectionID], [OfferID], [AssignmentID], [SummaryType])
CREATE INDEX CMN_missing_index_237444_237443 ON [CM_WP1].[dbo].[DeploymentSummary] ([Type]) INCLUDE ([SiteNumber], [CollectionID], [OfferID], [ModelID], [AssignmentID], [SummaryType])
CREATE INDEX CMN_missing_index_65389_65388 ON [CM_WP1].[dbo].[Collections_G] ([CollectionType]) INCLUDE ([CollectionID], [SiteID], [CollectionName], [LastRefreshRequest])
CREATE INDEX CMN_missing_index_444471_444470 ON [CM_WP1].[dbo].[CI_CIDocuments] ([Document_ID])
CREATE INDEX CMN_missing_index_4765672_4765671 ON [CM_WP1].[dbo].[System_DISC] ([Resource_Domain_OR_Workgr0], [Client0], [Decommissioned0],[ItemKey]) INCLUDE ([Netbios_Name0], [Obsolete0])
CREATE INDEX CMN_missing_index_1036910_1036909 ON [CM_WP1].[dbo].[BGB_ResTaskHistory] ([TaskID]) INCLUDE ([ResourceID])
CREATE INDEX CMN_missing_index_4640756_4640755 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey]) INCLUDE ([Resource_Domain_OR_Workgr0], [Obsolete0])
CREATE INDEX CMN_missing_index_5276666_5276665 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey]) INCLUDE ([Operating_System_Name_and0], [Obsolete0])
CREATE INDEX CMN_missing_index_965169_965168 ON [CM_WP1].[dbo].[BGB_ResTaskPush] ([TaskID], [PushID],[ResourceID])
CREATE INDEX CMN_missing_index_2825328_2825327 ON [CM_WP1].[dbo].[Logical_Disk_DATA] ([DeviceID00]) INCLUDE ([FreeSpace00], [Size00], [MachineID])
CREATE INDEX CMN_missing_index_5974089_5974088 ON [CM_WP1].[dbo].[Computer_System_DATA] ([Manufacturer00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_4624684_4624683 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([Netbios_Name0], [Full_Domain_Name0], [User_Name0])
CREATE INDEX CMN_missing_index_6377350_6377349 ON [CM_WP1].[dbo].[ClientKeyData] ([AADTenantID]) INCLUDE ([AADDeviceID])
CREATE INDEX CMN_missing_index_2476864_2476863 ON [CM_WP1].[dbo].[BGB_ResStatus] ([OnlineStatus], [ServerID]) INCLUDE ([ResourceID])
CREATE INDEX CMN_missing_index_5855829_5855828 ON [CM_WP1].[dbo].[HOD_HIST] ([TimeKey]) INCLUDE ([MachineID], [InstanceKey], [RevisionID])
CREATE INDEX CMN_missing_index_78146_78145 ON [CM_WP1].[dbo].[Folders] ([Name], [ObjectType], [ParentContainerNodeID], [SourceSite],[ContainerNodeID])
CREATE INDEX CMN_missing_index_4700113_4700112 ON [CM_WP1].[dbo].[System_DISC] ([AD_Site_Name0], [Client0], [ManagementAuthority]) INCLUDE ([Obsolete0], [Decommissioned0])
CREATE INDEX CMN_missing_index_4700155_4700154 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Client_Type0]) INCLUDE ([Obsolete0], [Decommissioned0])
CREATE INDEX CMN_missing_index_4700082_4700081 ON [CM_WP1].[dbo].[System_DISC] ([Client_Type0]) INCLUDE ([ItemKey], [DiscArchKey], [Decommissioned0])
CREATE INDEX CMN_missing_index_4700157_4700156 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Client_Type0]) INCLUDE ([ItemKey], [Obsolete0], [Decommissioned0])
CREATE INDEX CMN_missing_index_4700106_4700105 ON [CM_WP1].[dbo].[System_DISC] ([AADTenantID])
CREATE INDEX CMN_missing_index_4700108_4700107 ON [CM_WP1].[dbo].[System_DISC] ([AADDeviceID]) INCLUDE ([Client0])
CREATE INDEX CMN_missing_index_4700141_4700140 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey]) INCLUDE ([Client_Type0], [Obsolete0])
CREATE INDEX CMN_missing_index_4700111_4700110 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [ManagementAuthority],[AADDeviceID]) INCLUDE ([Obsolete0], [Decommissioned0])
CREATE INDEX CMN_missing_index_4700145_4700144 ON [CM_WP1].[dbo].[System_DISC] ([AADTenantID]) INCLUDE ([Client0], [AADDeviceID])
CREATE INDEX CMN_missing_index_4700151_4700150 ON [CM_WP1].[dbo].[System_DISC] ([AADTenantID]) INCLUDE ([Client0], [AADDeviceID])
CREATE INDEX CMN_missing_index_6268267_6268266 ON [CM_WP1].[dbo].[System_DISC] ([Resource_Domain_OR_Workgr0], [Decommissioned0],[ItemKey]) INCLUDE ([Operating_System_Name_and0], [Client0])
CREATE INDEX CMN_missing_index_4700061_4700060 ON [CM_WP1].[dbo].[System_DISC] ([Client0]) INCLUDE ([ItemKey], [Operating_System_Name_and0], [AgentEdition0], [Client_Version0], [Obsolete0], [Decommissioned0], [ManagementAuthority])
CREATE INDEX CMN_missing_index_78152_78151 ON [CM_WP1].[dbo].[Folders] ([ParentContainerNodeID]) INCLUDE ([ContainerNodeID], [Name])
CREATE INDEX CMN_missing_index_4629342_4629341 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([Netbios_Name0], [Client_Version0])
CREATE INDEX CMN_missing_index_4700147_4700146 ON [CM_WP1].[dbo].[User_DISC] ([AADTenantID]) INCLUDE ([AADUserID])
CREATE INDEX CMN_missing_index_4966167_4966166 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([Name0], [Operating_System_Name_and0], [AD_Site_Name0], [Client_Version0])
CREATE INDEX CMN_missing_index_4700289_4700288 ON [CM_WP1].[dbo].[System_DISC] ([Client0]) INCLUDE ([SMS_Unique_Identifier0], [Obsolete0], [Decommissioned0], [Virtual_Machine_Type0])
CREATE INDEX CMN_missing_index_4700056_4700055 ON [CM_WP1].[dbo].[System_DISC] ([Build01]) INCLUDE ([Obsolete0], [Decommissioned0], [OSBranch01])
CREATE INDEX CMN_missing_index_4700139_4700138 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [ManagementAuthority]) INCLUDE ([ItemKey], [Operating_System_Name_and0], [Client_Version0], [Obsolete0], [Decommissioned0], [Virtual_Machine_Type0], [Build01])
CREATE INDEX CMN_missing_index_1337123_1337122 ON [CM_WP1].[dbo].[Summarizer_ComponentTallys] ([TallyInterval]) INCLUDE ([ComponentDataID], [SiteNumber])
CREATE INDEX CMN_missing_index_2828076_2828075 ON [CM_WP1].[dbo].[Logical_Disk_DATA] ([DeviceID00],[FreeSpace00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_5855587_5855586 ON [CM_WP1].[dbo].[Logon_Banner_Group_Logon_Banner_64_HIST] ([TimeKey]) INCLUDE ([MachineID], [InstanceKey], [RevisionID])
CREATE INDEX CMN_missing_index_6589719_6589718 ON [CM_WP1].[dbo].[Network_DATA] ([DNSHostName00]) INCLUDE ([MachineID], [IPAddress00])
CREATE INDEX CMN_missing_index_965225_965224 ON [CM_WP1].[dbo].[BGB_ResTaskPush] ([PushID]) INCLUDE ([ResourceID], [TaskID])
CREATE INDEX CMN_missing_index_4629339_4629338 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Active0], [Decommissioned0],[ItemKey]) INCLUDE ([Netbios_Name0], [Name0])
CREATE INDEX CMN_missing_index_444474_444473 ON [CM_WP1].[dbo].[DeploymentSummary] ([AssignmentID]) INCLUDE ([SiteNumber], [OfferID], [SummaryType])
CREATE INDEX CMN_missing_index_5987505_5987504 ON [CM_WP1].[dbo].[Operating_System_DATA] ([Version00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_6164651_6164650 ON [CM_WP1].[dbo].[Operating_System_DATA] ([Caption00]) INCLUDE ([MachineID], [Version00], [Manufacturer00])
CREATE INDEX CMN_missing_index_928_927 ON [CM_WP1].[dbo].[DepPolicyAssignment] ([PolicyAssignmentID]) INCLUDE ([PADBID], [DepPADBID])
CREATE INDEX CMN_missing_index_227882_227881 ON [CM_WP1].[dbo].[PkgPrograms_G] ([Description]) INCLUDE ([ProgramID], [PkgID], [ProgramFlags])
CREATE INDEX CMN_missing_index_4021678_4021677 ON [CM_WP1].[dbo].[Flat_Group_User_Relationship_NS] ([SiteCode]) INCLUDE ([ID], [Group_ObjectGUID])
CREATE INDEX CMN_missing_index_1367386_1367385 ON [CM_WP1].[dbo].[Virtual_Applications_DATA] ([PackageGUID00]) INCLUDE ([LastLaunchOnSystem00], [Name00], [MachineID])
CREATE INDEX CMN_missing_index_118953_118952 ON [CM_WP1].[dbo].[APPV_CLIENT_APPLICATION_DATA] ([PackageId00]) INCLUDE ([MachineID], [TimeKey], [Name00])
CREATE INDEX CMN_missing_index_4671188_4671187 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([Netbios_Name0], [Resource_Domain_OR_Workgr0], [Client0])
CREATE INDEX CMN_missing_index_823111_823110 ON [CM_WP1].[dbo].[SMSPackages_G] ([Priority]) INCLUDE ([PkgID], [Name], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_156787_156786 ON [CM_WP1].[dbo].[EP_DeploymentState] ([DeploymentState])
CREATE INDEX CMN_missing_index_4595254_4595253 ON [CM_WP1].[dbo].[System_Enclosure_DATA] ([ChassisTypes00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_819946_819945 ON [CM_WP1].[dbo].[DBSchema] ([SiteNumber], [ObjectHash])
CREATE INDEX CMN_missing_index_141184_141183 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([IsTombstoned], [IsExpired],[CIType_ID]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_4781828_4781827 ON [CM_WP1].[dbo].[System_DISC] ([Resource_Domain_OR_Workgr0], [Client0], [Decommissioned0], [Is_Virtual_Machine0],[ItemKey]) INCLUDE ([DiscArchKey], [Netbios_Name0], [Operating_System_Name_and0], [AD_Site_Name0], [User_Name0], [Client_Type0], [Client_Version0], [Community_Name0], [User_Domain0], [CPUType0], [Hardware_ID0], [Obsolete0], [Creation_Date0])
CREATE INDEX CMN_missing_index_128408_128407 ON [CM_WP1].[dbo].[UserMachineTypeRelation] ([TypeID])
CREATE INDEX CMN_missing_index_128046_128045 ON [CM_WP1].[dbo].[Folders] ([ObjectType]) INCLUDE ([ContainerNodeID])
CREATE INDEX CMN_missing_index_6115705_6115704 ON [CM_WP1].[dbo].[Computer_System_DATA] ([Manufacturer00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_118274_118273 ON [CM_WP1].[dbo].[Virtual_Application_Packages_DATA] ([PackageGUID00]) INCLUDE ([MachineID], [TimeKey])
CREATE INDEX CMN_missing_index_6161644_6161643 ON [CM_WP1].[dbo].[Operating_System_DATA] ([LastBootUpTime00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_128470_128469 ON [CM_WP1].[dbo].[ADDiscoveryStats] ([StartTime]) INCLUDE ([AgentID], [IsFullSync], [DDRCount], [CompleteTime])
CREATE INDEX CMN_missing_index_602447_602446 ON [CM_WP1].[dbo].[CrpChange_Notify] ([CollectionID], [Flag])
CREATE INDEX CMN_missing_index_2871866_2871865 ON [CM_WP1].[dbo].[PC_BIOS_DATA] ([ReleaseDate00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_5687505_5687504 ON [CM_WP1].[dbo].[System_DISC] ([Unknown0], [Decommissioned0],[ItemKey], [Creation_Date0])
CREATE INDEX CMN_missing_index_4687042_4687041 ON [CM_WP1].[dbo].[User_DISC] ([User_Name0])
CREATE INDEX CMN_missing_index_4793863_4793862 ON [CM_WP1].[dbo].[System_DISC] ([Operating_System_Name_and0], [Client0], [Decommissioned0],[ItemKey]) INCLUDE ([Netbios_Name0], [Obsolete0])
CREATE INDEX CMN_missing_index_4641095_4641094 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0], [Is_Virtual_Machine0],[ItemKey]) INCLUDE ([Resource_Domain_OR_Workgr0], [Obsolete0])
CREATE INDEX CMN_missing_index_965223_965222 ON [CM_WP1].[dbo].[BGB_ResTaskPush] ([Status]) INCLUDE ([ResourceID], [TaskID], [PushID])
CREATE INDEX CMN_missing_index_6268262_6268261 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey], [Resource_Domain_OR_Workgr0]) INCLUDE ([Operating_System_Name_and0], [Client0])
CREATE INDEX CMN_missing_index_6268277_6268276 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([Operating_System_Name_and0], [Resource_Domain_OR_Workgr0], [Client0])
CREATE INDEX CMN_missing_index_6589717_6589716 ON [CM_WP1].[dbo].[System_DISC] ([Resource_Domain_OR_Workgr0], [Obsolete0], [Active0], [Decommissioned0],[ItemKey]) INCLUDE ([Netbios_Name0], [User_Name0], [Client0])
CREATE INDEX CMN_missing_index_4793800_4793799 ON [CM_WP1].[dbo].[System_DISC] ([Operating_System_Name_and0], [Client0], [Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [Netbios_Name0], [Resource_Domain_OR_Workgr0], [AD_Site_Name0], [User_Name0], [Client_Type0], [Client_Version0], [Community_Name0], [User_Domain0], [CPUType0], [Hardware_ID0], [Obsolete0], [Creation_Date0], [Is_Virtual_Machine0])
CREATE INDEX CMN_missing_index_4927222_4927221 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Obsolete0], [Active0], [Decommissioned0],[ItemKey]) INCLUDE ([Netbios_Name0], [User_Name0])
CREATE INDEX CMN_missing_index_5575926_5575925 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey], [Operating_System_Name_and0]) INCLUDE ([Netbios_Name0], [Obsolete0])
CREATE INDEX CMN_missing_index_218974_218973 ON [CM_WP1].[dbo].[Folders] ([Name], [ObjectType], [ParentContainerNodeID], [IsDeleted])
CREATE INDEX CMN_missing_index_218972_218971 ON [CM_WP1].[dbo].[Folders] ([Name], [ObjectType], [ParentContainerNodeID], [IsDeleted]) INCLUDE ([ContainerNodeID])
CREATE INDEX CMN_missing_index_4671482_4671481 ON [CM_WP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey], [Resource_Domain_OR_Workgr0]) INCLUDE ([Netbios_Name0], [Client0])
CREATE INDEX CMN_missing_index_118272_118271 ON [CM_WP1].[dbo].[APPV_CLIENT_PACKAGE_DATA] ([PackageId00]) INCLUDE ([MachineID], [TimeKey])
CREATE INDEX CMN_missing_index_2828022_2828021 ON [CM_WP1].[dbo].[Logical_Disk_DATA] ([DeviceID00]) INCLUDE ([FreeSpace00], [MachineID])
CREATE INDEX CMN_missing_index_3876159_3876158 ON [CM_WP1].[dbo].[vDCMDeploymentCIs] ([AssignmentID]) INCLUDE ([BL_ID], [CI_ID])
CREATE INDEX CMN_missing_index_3876157_3876156 ON [CM_WP1].[dbo].[vDCMDeploymentCIs] ([AssignmentID]) INCLUDE ([BL_ID], [CI_ID], [ModelId], [CIVersion])
CREATE INDEX CMN_missing_index_4627592_4627591 ON [CM_WP1].[dbo].[SoftwareProductMap] ([CompanyName])
CREATE INDEX CMN_missing_index_6571145_6571144 ON [CM_WP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey]) INCLUDE ([Netbios_Name0], [Operating_System_Name_and0], [Resource_Domain_OR_Workgr0], [Obsolete0])
CREATE INDEX CMN_missing_index_1709750_1709749 ON [CM_WP1].[dbo].[FolderMembers] ([ContainerNodeID]) INCLUDE ([MemberID], [InstanceKey])
CREATE INDEX CMN_missing_index_5385987_5385986 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([IsTombstoned]) INCLUDE ([ModelId], [CIVersion], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_3849911_3849910 ON [CM_WP1].[dbo].[vDCMDeploymentCIs] ([AssignmentID]) INCLUDE ([BL_ID], [CI_ID], [ModelId], [CIVersion], [SiteID])
CREATE INDEX CMN_missing_index_3640390_3640389 ON [CM_WP1].[dbo].[CM_UpdateFeatureLocalizedData] ([LocaleID])
CREATE INDEX CMN_missing_index_141176_141175 ON [CM_WP1].[dbo].[CI_UpdateCIs] ([UpdateSource_ID]) INCLUDE ([CI_ID], [DateRevised], [RevisionNumber])
CREATE INDEX CMN_missing_index_6091432_6091431 ON [CM_WP1].[dbo].[DotNETFrameworks_HIST] ([TimeKey]) INCLUDE ([MachineID], [InstanceKey], [RevisionID])
CREATE INDEX CMN_missing_index_6376876_6376875 ON [CM_WP1].[dbo].[Operating_System_DATA] ([InstallDate00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_6268307_6268306 ON [CM_WP1].[dbo].[DiscItemAgents] ([AgentID],[AgentTime]) INCLUDE ([ItemKey])
CREATE INDEX CMN_missing_index_681273_681272 ON [CM_WP1].[dbo].[CrpResourceChg_Notify] ([DeviceItemkey], [Flag])
CREATE INDEX CMN_missing_index_681275_681274 ON [CM_WP1].[dbo].[CrpResourceChg_Notify] ([Flag]) INCLUDE ([DeviceItemkey])
CREATE INDEX CMN_missing_index_1635343_1635342 ON [CM_WP1].[dbo].[BGB_ResStatus] ([ServerID],[OnlineStatus]) INCLUDE ([ResourceID])
CREATE INDEX CMN_missing_index_102437_102436 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([IsTombstoned]) INCLUDE ([CI_ID], [ModelId], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_92149_92148 ON [CM_WP1].[dbo].[SMSPackages_G] ([Name]) INCLUDE ([PkgID], [PackageType], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_128394_128393 ON [CM_WP1].[dbo].[CI_CurrentErrorDetails] ([CI_ID]) INCLUDE ([ErrorCode])
CREATE INDEX CMN_missing_index_220210_220209 ON [CM_WP1].[dbo].[Collections_L] ([CurrentStatus]) INCLUDE ([CollectionID])
CREATE INDEX CMN_missing_index_6462167_6462166 ON [CM_WP1].[dbo].[PkgStatus_L] ([Type]) INCLUDE ([ID], [PkgServer], [Status], [SourceVersion])
CREATE INDEX CMN_missing_index_76551_76550 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([IsHidden], [IsTombstoned],[CIType_ID]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_3748386_3748385 ON [CM_WP1].[dbo].[SMSPackages_G] ([PackageType]) INCLUDE ([PkgID])
CREATE INDEX CMN_missing_index_128465_128464 ON [CM_WP1].[dbo].[Collections_G] ([CollectionType]) INCLUDE ([CollectionID])
CREATE INDEX CMN_missing_index_6377346_6377345 ON [CM_WP1].[dbo].[ClientDeploymentState] ([ItemKey]) INCLUDE ([DeploymentMethod])
CREATE INDEX CMN_missing_index_6377387_6377386 ON [CM_WP1].[dbo].[ClientDeploymentState] ([ItemKey]) INCLUDE ([LastMessageStateID], [ClientVersion], [LastErrorCode])
CREATE INDEX CMN_missing_index_6056390_6056389 ON [CM_WP1].[dbo].[WorkstationStatus_DATA] ([LastHWScan])
CREATE INDEX CMN_missing_index_6504906_6504905 ON [CM_WP1].[dbo].[StatusMessages] ([MachineName],[Component]) INCLUDE ([RecordID], [MessageID], [Time])
CREATE INDEX CMN_missing_index_6268309_6268308 ON [CM_WP1].[dbo].[DiscItemAgents] ([AgentTime]) INCLUDE ([ItemKey], [AgentID])
CREATE INDEX CMN_missing_index_156775_156774 ON [CM_WP1].[dbo].[ClientPushMachine_G] ([LatestProcessingAttempt]) INCLUDE ([ID])
CREATE INDEX CMN_missing_index_6376858_6376857 ON [CM_WP1].[dbo].[ClientDeploymentState] ([BaselineType]) INCLUDE ([ItemKey], [SourceType])
CREATE INDEX CMN_missing_index_6268311_6268310 ON [CM_WP1].[dbo].[ClientDeploymentState] ([AssignedSiteCode]) INCLUDE ([RecordID])
CREATE INDEX CMN_missing_index_3556511_3556510 ON [CM_WP1].[dbo].[Windows_Update_Agent__DATA] ([Version00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_5687466_5687465 ON [CM_WP1].[dbo].[UserMachineRelation] ([RelationActive],[MachineResourceID]) INCLUDE ([RelationshipResourceID], [InactivationTime])
CREATE INDEX CMN_missing_index_3234479_3234478 ON [CM_WP1].[dbo].[SMSPackages_G] ([Name])
CREATE INDEX CMN_missing_index_776355_776354 ON [CM_WP1].[dbo].[Flat_Group_System_Relationship] ([SiteCode]) INCLUDE ([ID], [Group_ObjectGUID])
CREATE INDEX CMN_missing_index_6093382_6093381 ON [CM_WP1].[dbo].[QUICK_FIX_ENGINEERING_DATA] ([MachineID], [HotFixID00])
CREATE INDEX CMN_missing_index_4700163_4700162 ON [CM_WP1].[dbo].[Update_ScanStatus] ([LastErrorCode])
CREATE INDEX CMN_missing_index_4463997_4463996 ON [CM_WP1].[dbo].[CollectionMembers] ([SiteID],[ArchitectureKey], [SMSID]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_4625500_4625499 ON [CM_WP1].[dbo].[Update_ScanStatus] ([LastErrorCode]) INCLUDE ([MachineID], [LastScanTime])
CREATE INDEX CMN_missing_index_128406_128405 ON [CM_WP1].[dbo].[EP_DeploymentState] ([ErrorCode]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_6571143_6571142 ON [CM_WP1].[dbo].[ROOT_CA_DATA] ([Subject00]) INCLUDE ([Thumbprint00])
CREATE INDEX CMN_missing_index_608385_608384 ON [CM_WP1].[dbo].[PfxAssignment_Notify] ([Flag]) INCLUDE ([ID], [CollectionID])
CREATE INDEX CMN_missing_index_3625864_3625863 ON [CM_WP1].[dbo].[OSD64_DATA] ([PXE00]) INCLUDE ([MachineID], [DeployedBy00], [ImageInstalled00], [SMSTSRole00], [TaskSequence00])
CREATE INDEX CMN_missing_index_3853139_3853138 ON [CM_WP1].[dbo].[CI_CurrentErrorDetails] ([CI_ID], [ErrorType], [IsRuleOnSetting]) INCLUDE ([CurrentComplianceStatusID], [ErrorCode])
CREATE INDEX CMN_missing_index_5959499_5959498 ON [CM_WP1].[dbo].[COMPUTER_SYSTEM_PRODUCT_DATA] ([Version00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_3853141_3853140 ON [CM_WP1].[dbo].[CI_CurrentErrorDetails] ([ErrorType], [IsRuleOnSetting]) INCLUDE ([CurrentComplianceStatusID], [CI_ID], [ErrorCode])
CREATE INDEX CMN_missing_index_2822985_2822984 ON [CM_WP1].[dbo].[CI_CurrentErrorDetails] ([SettingID]) INCLUDE ([RecordID])
CREATE INDEX CMN_missing_index_141214_141213 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([IsHidden], [IsTombstoned], [IsExpired],[CIType_ID]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_1840163_1840162 ON [msdb].[dbo].[backupset] ([type]) INCLUDE ([backup_finish_date], [database_name])
CREATE INDEX CMN_missing_index_128412_128411 ON [CM_WP1].[dbo].[Collections_G] ([CollectionType]) INCLUDE ([CollectionID], [SiteID], [LastRefreshRequest])
CREATE INDEX CMN_missing_index_4700059_4700058 ON [CM_WP1].[dbo].[SMSPackages_G] ([Action]) INCLUDE ([PkgID])
CREATE INDEX CMN_missing_index_92134_92133 ON [CM_WP1].[dbo].[SoftwarePolicy] ([DepSourceID]) INCLUDE ([PolicyID], [PkgID], [ProgramName])
CREATE INDEX CMN_missing_index_858564_858563 ON [CM_WP1].[dbo].[Group_ImmediateSearchBase] ([SearchBaseID]) INCLUDE ([Group_ObjectGUID])
CREATE INDEX CMN_missing_index_9891_9890 ON [CM_WP1].[dbo].[Collections_L] ([EvaluationGQStatus]) INCLUDE ([CollectionID])
CREATE INDEX CMN_missing_index_105_104 ON [CM_WP1].[dbo].[SEDO_LockRequests] ([RequestTime]) INCLUDE ([ID])
CREATE INDEX CMN_missing_index_2529574_2529573 ON [CM_WP1].[dbo].[ActiveDirectoryObjectInfo] ([SiteCode],[LastRefreshTime]) INCLUDE ([ObjectGUID])
CREATE INDEX CMN_missing_index_220201_220200 ON [CM_WP1].[dbo].[Collections_L] ([EvaluationStartTime], [LastRefreshTime]) INCLUDE ([CollectionID], [MemberChanges], [EvaluationLength], [LastMemberChangeTime])
CREATE INDEX CMN_missing_index_5383966_5383965 ON [CM_WP1].[dbo].[ProgramOffers_G] ([Action]) INCLUDE ([OfferID], [PkgID], [PkgProgram], [CollectionID], [PresentTime], [OfferFlags], [Deadline], [LastModificationTime], [OfferTypeID])
CREATE INDEX CMN_missing_index_608383_608382 ON [CM_WP1].[dbo].[CrpChange_Notify] ([Flag]) INCLUDE ([ID], [CollectionID])
CREATE INDEX CMN_missing_index_792763_792762 ON [CM_WP1].[dbo].[FolderMembers] ([IsDeleted],[ContainerNodeID]) INCLUDE ([InstanceKey])
CREATE INDEX CMN_missing_index_2830149_2830148 ON [CM_WP1].[dbo].[CI_ConfigurationItemsOptionalRelations] ([RelationType], [IsVersionSpecific]) INCLUDE ([FromCI_ID], [ToCI_ID])
CREATE INDEX CMN_missing_index_128463_128462 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([IsTombstoned], [IsExpired]) INCLUDE ([CI_ID], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_2817175_2817174 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([CIType_ID], [IsHidden], [IsTombstoned], [IsEnabled], [IsLatest]) INCLUDE ([CI_ID], [CI_UniqueID], [ModelId])
CREATE INDEX CMN_missing_index_322_321 ON [CM_WP1].[dbo].[ConsoleUsageData] ([ConsoleConnectTime]) INCLUDE ([ID])
CREATE INDEX CMN_missing_index_5572502_5572501 ON [CM_WP1].[dbo].[RBAC_InstancePermissions] ([ObjectTypeID],[AdminID]) INCLUDE ([ObjectKey], [GrantedOperations])
CREATE INDEX CMN_missing_index_220205_220204 ON [CM_WP1].[dbo].[Collections_L] ([IncrementalEvaluationStartTime], [LastIncrementalRefreshTime]) INCLUDE ([CollectionID], [IncrementalMemberChanges], [LastMemberChangeTime])
CREATE INDEX CMN_missing_index_278236_278235 ON [msdb].[dbo].[backupset] ([backup_finish_date]) INCLUDE ([media_set_id])
CREATE INDEX CMN_missing_index_952659_952658 ON [CM_WP1].[dbo].[SoftwarePolicy] ([OfferID]) INCLUDE ([PADBID], [PkgID])
CREATE INDEX CMN_missing_index_5584881_5584880 ON [CM_WP1].[dbo].[SMSPackages_G] ([Name], [Manufacturer])
CREATE INDEX CMN_missing_index_3234554_3234553 ON [CM_WP1].[dbo].[SMSPackages_G] ([Source]) INCLUDE ([MinRequiredVersion])
CREATE INDEX CMN_missing_index_3234481_3234480 ON [CM_WP1].[dbo].[SMSPackages_G] ([Source]) INCLUDE ([PkgID], [Name], [SourceSite], [PackageType], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_2871760_2871759 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([CIType_ID], [IsEnabled], [IsExpired], [IsLatest]) INCLUDE ([CI_ID], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_379117_379116 ON [CM_WP1].[dbo].[ClientPushMachine_G] ([PushSiteCode], [Status]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_5087134_5087133 ON [CM_WP1].[dbo].[System_DISC] ([Obsolete0], [Decommissioned0],[ItemKey])
CREATE INDEX CMN_missing_index_5255679_5255678 ON [msdb].[dbo].[backupset] ([type],[database_name]) INCLUDE ([backup_finish_date])
CREATE INDEX CMN_missing_index_2393309_2393308 ON [CM_WP1].[dbo].[SoftwarePolicy] ([PkgID], [ProgramName]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_128436_128435 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([IsHidden], [IsTombstoned], [IsExpired],[CIType_ID])
CREATE INDEX CMN_missing_index_621019_621018 ON [CM_WP1].[dbo].[PfxAssignment_Notify] ([Flag])
CREATE INDEX CMN_missing_index_128439_128438 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([IsHidden], [IsTombstoned],[CIType_ID])
CREATE INDEX CMN_missing_index_4124689_4124688 ON [CM_WP1].[dbo].[Folders] ([ObjectType],[ContainerNodeID])
CREATE INDEX CMN_missing_index_2871464_2871463 ON [CM_WP1].[dbo].[CI_ConfigurationItems] ([CIType_ID], [IsTombstoned], [IsEnabled], [IsExpired], [IsLatest]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_4859642_4859641 ON [CM_WP1].[dbo].[CI_CIAssignments] ([IsTombstoned], [AssignmentType]) INCLUDE ([AssignmentID], [Assignment_UniqueID])
CREATE INDEX CMN_missing_index_4859644_4859643 ON [CM_WP1].[dbo].[CI_CIAssignments] ([IsTombstoned], [AssignmentType])
CREATE INDEX CMN_missing_index_128507_128506 ON [CM_WP1].[dbo].[Firmware_DATA] ([SecureBoot00])
CREATE INDEX CMN_missing_index_128503_128502 ON [CM_WP1].[dbo].[TPM_STATUS_DATA] ([IsApplicable00])
CREATE INDEX CMN_missing_index_4656206_4656205 ON [CM_WP1].[dbo].[CI_CIAssignments] ([AssignmentName], [IsTombstoned],[AssignmentType])
CREATE INDEX CMN_missing_index_5593915_5593914 ON [CM_WP1].[dbo].[vDCMDeploymentCIs] ([AssignmentID]) INCLUDE ([CI_ID], [ModelId], [CIVersion])
CREATE INDEX CMN_missing_index_636132_636131 ON [CM_WP1].[dbo].[CrpChange_Notify] ([Flag])
CREATE INDEX CMN_missing_index_654504_654503 ON [CM_WP1].[dbo].[PfxAssignment_Notify] ([CollectionID])
CREATE INDEX CMN_missing_index_654502_654501 ON [CM_WP1].[dbo].[CrpChange_Notify] ([CollectionID])
