CREATE INDEX CMN_missing_index_17599_17598 ON [CM_SP1].[dbo].[System_DISC] ([ManagementAuthority]) INCLUDE ([SMS_Unique_Identifier0])
CREATE INDEX CMN_missing_index_16_15 ON [CM_SP1].[dbo].[AttributeMap] ([GroupKey], [IsKey])
CREATE INDEX CMN_missing_index_18_17 ON [CM_SP1].[dbo].[AttributeMap] ([IsKey]) INCLUDE ([GroupKey])
CREATE INDEX CMN_missing_index_17822_17821 ON [CM_SP1].[dbo].[Update_ComplianceStatus] ([Status]) INCLUDE ([CI_ID], [MachineID], [EnforcementSource], [LastEnforcementMessageID])
CREATE INDEX CMN_missing_index_17609_17608 ON [CM_SP1].[dbo].[Update_ComplianceStatus] ([MachineID],[LastStatusCheckTime], [LastEnforcementMessageTime]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_17611_17610 ON [CM_SP1].[dbo].[Update_ComplianceStatus] ([MachineID]) INCLUDE ([CI_ID], [Status], [LastStatusCheckTime], [LastEnforcementMessageID], [rowversion])
CREATE INDEX CMN_missing_index_17607_17606 ON [CM_SP1].[dbo].[CI_CurrentComplianceStatus] ([ItemKey],[LastComplianceMessageTime], [LastEnforcementMessageTime], [LastLaunchStateMessageTime]) INCLUDE ([CI_CurrentComplianceStatusID])
CREATE INDEX CMN_missing_index_213_212 ON [CM_SP1].[dbo].[SoftwarePolicy] ([OfferID], [PkgID]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_17683_17682 ON [CM_SP1].[dbo].[Update_ComplianceStatus] ([EnforcementSource],[LastEnforcementMessageID], [LastEnforcementMessageTime]) INCLUDE ([CI_ID], [MachineID])
CREATE INDEX CMN_missing_index_308_307 ON [CM_SP1].[dbo].[DepPolicyAssignment] ([DepPADBID]) INCLUDE ([PADBID], [IsTombstoned])
CREATE INDEX CMN_missing_index_6_5 ON [ReportServer].[dbo].[ExecutionLogStorage] ([ReportAction]) INCLUDE ([ReportID], [TimeStart])
CREATE INDEX CMN_missing_index_17597_17596 ON [CM_SP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([Client0], [Client_Type0], [Obsolete0])
CREATE INDEX CMN_missing_index_11_10 ON [CM_SP1].[dbo].[Collections_G] ([SiteID]) INCLUDE ([LimitToCollectionID])
CREATE INDEX CMN_missing_index_376_375 ON [msdb].[dbo].[sysjobhistory] ([job_id], [step_id], [run_date], [run_time])
CREATE INDEX CMN_missing_index_217_216 ON [CM_SP1].[dbo].[RBAC_InstancePermissions] ([ObjectTypeID]) INCLUDE ([AdminID], [ObjectKey], [GrantedOperations])
CREATE INDEX CMN_missing_index_19688_19687 ON [CM_SP1].[dbo].[Update_ComplianceStatus] ([LastEnforcementMessageID],[Status]) INCLUDE ([CI_ID], [MachineID])
CREATE INDEX CMN_missing_index_262_261 ON [msdb].[dbo].[sysjobhistory] ([step_id]) INCLUDE ([instance_id], [job_id], [run_date], [run_time])
CREATE INDEX CMN_missing_index_10698_10697 ON [CM_SP1].[dbo].[DeploymentSummary] ([OfferID])
CREATE INDEX CMN_missing_index_228_227 ON [CM_SP1].[dbo].[Collection_Rules] ([RuleType],[MachineID]) INCLUDE ([CollectionID], [ArchitectureKey])
CREATE INDEX CMN_missing_index_85_84 ON [CM_SP1].[dbo].[BGB_ResStatus] ([ServerID]) INCLUDE ([ResourceID], [OnlineStatus])
CREATE INDEX CMN_missing_index_19132_19131 ON [CM_SP1].[dbo].[Update_ComplianceStatus] ([Status],[LastEnforcementMessageID]) INCLUDE ([MachineID], [LastEnforcementMessageTime])
CREATE INDEX CMN_missing_index_4_3 ON [ReportServer].[dbo].[Catalog] ([Type]) INCLUDE ([ModifiedDate])
CREATE INDEX CMN_missing_index_264_263 ON [msdb].[dbo].[sysjobhistory] ([step_id]) INCLUDE ([instance_id], [job_id], [run_status], [run_date], [run_time], [run_duration])
CREATE INDEX CMN_missing_index_233_232 ON [CM_SP1].[dbo].[CollectionNotifications] ([Group_ObjectGUID],[RecordID]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_230_229 ON [CM_SP1].[dbo].[CollectionNotifications] ([TableName],[RecordID], [MachineID])
CREATE INDEX CMN_missing_index_310_309 ON [CM_SP1].[dbo].[DepPolicyAssignment] ([IsTombstoned]) INCLUDE ([PADBID], [DepPADBID])
CREATE INDEX CMN_missing_index_18051_18050 ON [CM_SP1].[dbo].[UserMachineRelation] ([MachineResourceID], [RelationActive])
CREATE INDEX CMN_missing_index_352_351 ON [CM_SP1].[dbo].[CI_ConfigurationItems] ([IsTombstoned], [IsExpired], [SourceSite],[CIType_ID]) INCLUDE ([CI_ID], [DateCreated], [DateLastModified])
CREATE INDEX CMN_missing_index_17854_17853 ON [CM_SP1].[dbo].[StatusMessages] ([DeleteTime]) INCLUDE ([RecordID])
CREATE INDEX CMN_missing_index_89_88 ON [CM_SP1].[dbo].[PkgServers_L] ([NALPath])
CREATE INDEX CMN_missing_index_19123_19122 ON [CM_SP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([Name0])
CREATE INDEX CMN_missing_index_11324_11323 ON [CM_SP1].[dbo].[UserMachineSourceRelation] ([SourceID]) INCLUDE ([RelationshipResourceID])
CREATE INDEX CMN_missing_index_20980_20979 ON [CM_SP1].[dbo].[Add_Remove_Programs_DATA] ([DisplayName00]) INCLUDE ([MachineID], [Publisher00], [Version00])
CREATE INDEX CMN_missing_index_87_86 ON [CM_SP1].[dbo].[SR_ClientMessageStats] ([LastResyncIssuedTime]) INCLUDE ([MachineID], [LastResyncClientCompletedTime])
CREATE INDEX CMN_missing_index_11320_11319 ON [CM_SP1].[dbo].[UserMachineSourceRelation] ([SourceID]) INCLUDE ([RelationshipResourceID])
CREATE INDEX CMN_missing_index_313_312 ON [CM_SP1].[dbo].[PolicyAssignment] ([PolicyAssignmentID])
CREATE INDEX CMN_missing_index_78_77 ON [ReportServer].[dbo].[PolicyUserRole] ([PolicyID]) INCLUDE ([RoleID], [UserID])
CREATE INDEX CMN_missing_index_243_242 ON [msdb].[dbo].[backupfile] ([file_type]) INCLUDE ([backup_set_id], [file_number])
CREATE INDEX CMN_missing_index_247_246 ON [msdb].[dbo].[backupfile] ([file_type]) INCLUDE ([backup_set_id], [file_number])
CREATE INDEX CMN_missing_index_14613_14612 ON [CM_SP1].[dbo].[INSTALLED_SOFTWARE_HIST] ([TimeKey]) INCLUDE ([MachineID], [InstanceKey], [RevisionID])
CREATE INDEX CMN_missing_index_21322_21321 ON [CM_SP1].[dbo].[CI_ConfigurationItems] ([IsTombstoned]) INCLUDE ([ConfigurationFlags])
CREATE INDEX CMN_missing_index_20982_20981 ON [CM_SP1].[dbo].[Add_Remove_Programs_64_DATA] ([DisplayName00]) INCLUDE ([MachineID], [Publisher00], [Version00])
CREATE INDEX CMN_missing_index_17993_17992 ON [CM_SP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Operating_System_Name_and0], [Resource_Domain_OR_Workgr0])
CREATE INDEX CMN_missing_index_18757_18756 ON [CM_SP1].[dbo].[ResOfferCollMap] ([OfferID]) INCLUDE ([MachineID], [CollectionID])
CREATE INDEX CMN_missing_index_18473_18472 ON [CM_SP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey], [Operating_System_Name_and0]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Resource_Domain_OR_Workgr0])
CREATE INDEX CMN_missing_index_2_1 ON [CM_SP1].[dbo].[SoftwarePolicy] ([PADBID]) INCLUDE ([PkgID], [ProgramName])
CREATE INDEX CMN_missing_index_235_234 ON [CM_SP1].[dbo].[Collections_G] ([Schedule]) INCLUDE ([CollectionID], [Flags])
CREATE INDEX CMN_missing_index_241_240 ON [msdb].[dbo].[backupset] ([type]) INCLUDE ([backup_set_id], [backup_finish_date], [database_name])
CREATE INDEX CMN_missing_index_245_244 ON [msdb].[dbo].[backupset] ([type]) INCLUDE ([backup_set_id], [backup_finish_date], [database_name])
CREATE INDEX CMN_missing_index_14778_14777 ON [CM_SP1].[dbo].[LU_SoftwareList] ([SourceSite],[LastUpdated])
CREATE INDEX CMN_missing_index_12496_12495 ON [CM_SP1].[dbo].[PolicyAssignment] ([PolicyAssignmentID]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_18036_18035 ON [CM_SP1].[dbo].[System_DISC] ([Resource_Domain_OR_Workgr0], [Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Client0])
CREATE INDEX CMN_missing_index_25955_25954 ON [CM_SP1].[dbo].[CI_ConfigurationItems] ([CIType_ID]) INCLUDE ([CI_ID], [ModelId], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_17869_17868 ON [CM_SP1].[dbo].[CollectionMembers] ([SiteID], [ArchitectureKey],[MachineID], [SMSID])
CREATE INDEX CMN_missing_index_102_101 ON [CM_SP1].[dbo].[FolderMembers] ([ContainerNodeID], [IsDeleted])
CREATE INDEX CMN_missing_index_363_362 ON [CM_SP1].[dbo].[BGB_ResStatus] ([ServerID]) INCLUDE ([OnlineStatus])
CREATE INDEX CMN_missing_index_359_358 ON [CM_SP1].[dbo].[DeploymentSummary] ([AssignmentID]) INCLUDE ([SummarizationTime])
CREATE INDEX CMN_missing_index_19141_19140 ON [CM_SP1].[dbo].[System_DISC] ([Client0], [Active0], [Decommissioned0],[ItemKey]) INCLUDE ([Operating_System_Name_and0])
CREATE INDEX CMN_missing_index_14780_14779 ON [CM_SP1].[dbo].[LU_SoftwareHash] ([SourceSite],[LastUpdated])
CREATE INDEX CMN_missing_index_19121_19120 ON [CM_SP1].[dbo].[System_DISC] ([Name0], [Decommissioned0],[ItemKey])
CREATE INDEX CMN_missing_index_12403_12402 ON [CM_SP1].[dbo].[DiscItemAgents] ([AgentID]) INCLUDE ([ItemKey], [AgentTime])
CREATE INDEX CMN_missing_index_17991_17990 ON [CM_SP1].[dbo].[System_DISC] ([Resource_Domain_OR_Workgr0], [Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Netbios_Name0], [Name0], [Client0])
CREATE INDEX CMN_missing_index_19144_19143 ON [CM_SP1].[dbo].[System_DISC] ([Client0], [Active0], [Decommissioned0],[ItemKey]) INCLUDE ([Netbios_Name0], [Name0])
CREATE INDEX CMN_missing_index_7619_7618 ON [CM_SP1].[dbo].[ClientDeploymentState] ([BaselineCookie]) INCLUDE ([RecordID], [SMSID], [InstalledLangs])
CREATE INDEX CMN_missing_index_105_104 ON [CM_SP1].[dbo].[FolderMembers] ([IsDeleted]) INCLUDE ([ContainerNodeID])
CREATE INDEX CMN_missing_index_11397_11396 ON [CM_SP1].[dbo].[Library_ImportedObjects] ([ObjectTypeID], [ObjectKey]) INCLUDE ([ImportID])
CREATE INDEX CMN_missing_index_19139_19138 ON [CM_SP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey]) INCLUDE ([Client_Version0], [Obsolete0])
CREATE INDEX CMN_missing_index_12492_12491 ON [CM_SP1].[dbo].[PolicyAssignment] ([IsTombstoned]) INCLUDE ([PADBID], [PolicyAssignmentID])
CREATE INDEX CMN_missing_index_11489_11488 ON [CM_SP1].[dbo].[MachineIdGroupXRef] ([ArchitectureKey],[MachineID]) INCLUDE ([GUID])
CREATE INDEX CMN_missing_index_95_94 ON [CM_SP1].[dbo].[ContentDistributionMessages] ([DPID]) INCLUDE ([DistributionID])
CREATE INDEX CMN_missing_index_21436_21435 ON [CM_SP1].[SCCM_Ext].[RecentlyUsedApps_DATA_DD] ([DelDate]) INCLUDE ([rowversion])
CREATE INDEX CMN_missing_index_11399_11398 ON [CM_SP1].[dbo].[Library_ImportedObjects] ([ObjectTypeID]) INCLUDE ([ImportID], [ObjectKey])
CREATE INDEX CMN_missing_index_18314_18313 ON [CM_SP1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Resource_Domain_OR_Workgr0], [Creation_Date0])
CREATE INDEX CMN_missing_index_11700_11699 ON [CM_SP1].[dbo].[SCCM_Audit] ([ChangeTime]) INCLUDE ([ID])
CREATE INDEX CMN_missing_index_17614_17613 ON [CM_SP1].[dbo].[ResPolicyMap] ([IsTombstoned],[LastUpdateTime]) INCLUDE ([MachineID], [PADBID])
CREATE INDEX CMN_missing_index_17616_17615 ON [CM_SP1].[dbo].[PolicyAssignment] ([IsTombstoned]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_20691_20690 ON [CM_SP1].[dbo].[UserMachineRelation] ([RelationActive]) INCLUDE ([RelationshipResourceID])
CREATE INDEX CMN_missing_index_11923_11922 ON [CM_SP1].[dbo].[PowerShell_DATA] ([PowerShellVersion00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_270_269 ON [CM_SP1].[dbo].[DeploymentSummary] ([OfferID],[Type]) INCLUDE ([NumberInstalled], [NumberInProgress], [NumberUnknown], [NumberErrors], [NumberReqsNotMet], [SummarizationTime])
CREATE INDEX CMN_missing_index_361_360 ON [CM_SP1].[dbo].[DeploymentSummary] ([OfferID]) INCLUDE ([SummarizationTime])
CREATE INDEX CMN_missing_index_17618_17617 ON [CM_SP1].[dbo].[ResPolicyMap] ([IsTombstoned]) INCLUDE ([MachineID], [PADBID])
CREATE INDEX CMN_missing_index_21237_21236 ON [CM_SP1].[dbo].[System_DISC] ([AD_Site_Name0], [Client0], [ManagementAuthority]) INCLUDE ([Obsolete0], [Decommissioned0])
CREATE INDEX CMN_missing_index_12416_12415 ON [CM_SP1].[dbo].[ClientDeploymentState] ([LastMessageTime]) INCLUDE ([LastMessageStateID])
CREATE INDEX CMN_missing_index_21274_21273 ON [CM_SP1].[dbo].[System_DISC] ([Client0], [Client_Type0]) INCLUDE ([Obsolete0], [Decommissioned0])
CREATE INDEX CMN_missing_index_21220_21219 ON [CM_SP1].[dbo].[System_DISC] ([Client_Type0]) INCLUDE ([ItemKey], [DiscArchKey], [Decommissioned0])
CREATE INDEX CMN_missing_index_21231_21230 ON [CM_SP1].[dbo].[System_DISC] ([AADTenantID])
CREATE INDEX CMN_missing_index_21276_21275 ON [CM_SP1].[dbo].[System_DISC] ([Client0], [Client_Type0]) INCLUDE ([ItemKey], [Obsolete0], [Decommissioned0])
CREATE INDEX CMN_missing_index_21233_21232 ON [CM_SP1].[dbo].[System_DISC] ([AADDeviceID]) INCLUDE ([Client0])
CREATE INDEX CMN_missing_index_21235_21234 ON [CM_SP1].[dbo].[System_DISC] ([Client0], [ManagementAuthority],[AADDeviceID]) INCLUDE ([Obsolete0], [Decommissioned0])
CREATE INDEX CMN_missing_index_950_949 ON [CM_SP1].[dbo].[CI_ConfigurationItems] ([IsTombstoned],[CI_ID])
CREATE INDEX CMN_missing_index_21270_21269 ON [CM_SP1].[dbo].[System_DISC] ([AADTenantID]) INCLUDE ([Client0], [AADDeviceID])
CREATE INDEX CMN_missing_index_11271_11270 ON [CM_SP1].[dbo].[SoftwarePolicy] ([OfferID]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_11870_11869 ON [CM_SP1].[dbo].[TERMINAL_SERVICE_SETTING_DATA] ([TerminalServerMode00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_11203_11202 ON [CM_SP1].[dbo].[PkgStatus_L] ([Type]) INCLUDE ([ID], [PkgServer], [Status], [SourceVersion])
CREATE INDEX CMN_missing_index_343_342 ON [CM_SP1].[dbo].[PkgStatus_L] ([Type], [PkgServer]) INCLUDE ([ID])
CREATE INDEX CMN_missing_index_21216_21215 ON [CM_SP1].[dbo].[System_DISC] ([Build01]) INCLUDE ([Obsolete0], [Decommissioned0], [OSBranch01])
CREATE INDEX CMN_missing_index_21325_21324 ON [CM_SP1].[dbo].[System_DISC] ([Client0]) INCLUDE ([SMS_Unique_Identifier0], [Obsolete0], [Decommissioned0], [Virtual_Machine_Type0])
CREATE INDEX CMN_missing_index_11273_11272 ON [CM_SP1].[dbo].[SoftwarePolicy] ([OfferID], [ParentPolicyID]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_19772_19771 ON [CM_SP1].[dbo].[Operating_System_DATA] ([Caption00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_11263_11262 ON [ReportServer].[dbo].[Catalog] ([Type]) INCLUDE ([ParentID])
CREATE INDEX CMN_missing_index_20110_20109 ON [CM_SP1].[dbo].[Update_DetectionStatus] ([StatusTime]) INCLUDE ([CI_UniqueID], [MachineID])
CREATE INDEX CMN_missing_index_303_302 ON [CM_SP1].[dbo].[SoftwarePolicy] ([OfferID])
CREATE INDEX CMN_missing_index_345_344 ON [CM_SP1].[dbo].[PkgStatus_L] ([Type]) INCLUDE ([ID], [PkgServer])
CREATE INDEX CMN_missing_index_11265_11264 ON [ReportServer].[dbo].[Catalog] ([Type]) INCLUDE ([ItemID], [Path], [ParentID], [Description], [Hidden], [CreationDate])
CREATE INDEX CMN_missing_index_14784_14783 ON [CM_SP1].[dbo].[DiscItemAgents] ([DiscArchKey]) INCLUDE ([ItemKey], [AgentTime])
CREATE INDEX CMN_missing_index_21007_21006 ON [CM_SP1].[dbo].[Operating_System_DATA] ([Caption00]) INCLUDE ([MachineID], [Version00], [Manufacturer00])
CREATE INDEX CMN_missing_index_21272_21271 ON [CM_SP1].[dbo].[ClientKeyData] ([AADTenantID]) INCLUDE ([AADDeviceID])
CREATE INDEX CMN_missing_index_83_82 ON [CM_SP1].[dbo].[BGB_ResTaskPush] ([PushID]) INCLUDE ([ResourceID], [TaskID])
CREATE INDEX CMN_missing_index_438_437 ON [CM_SP1].[dbo].[CI_SettingReferences] ([Rule_ID]) INCLUDE ([Setting_ID])
CREATE INDEX CMN_missing_index_19118_19117 ON [CM_SP1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([Client0], [Obsolete0])
CREATE INDEX CMN_missing_index_13056_13055 ON [CM_SP1].[dbo].[CI_ConfigurationItems] ([IsTombstoned]) INCLUDE ([CI_UniqueID])
CREATE INDEX CMN_missing_index_5407_5406 ON [CM_SP1].[dbo].[BGB_ResTask] ([TaskID]) INCLUDE ([ResourceID])
CREATE INDEX CMN_missing_index_12248_12247 ON [CM_SP1].[dbo].[CI_ConfigurationItems] ([IsTombstoned], [IsExpired],[CIType_ID]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_11920_11919 ON [CM_SP1].[dbo].[System_DATA] ([Name0]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_315_314 ON [CM_SP1].[dbo].[SoftwarePolicy] ([PkgID], [ProgramName], [ParentPolicyID],[OfferID])
CREATE INDEX CMN_missing_index_301_300 ON [CM_SP1].[dbo].[SoftwarePolicy] ([ParentPolicyID],[OfferID])
CREATE INDEX CMN_missing_index_12494_12493 ON [CM_SP1].[dbo].[DepPolicyAssignment] ([PolicyAssignmentID]) INCLUDE ([PADBID], [DepPADBID])
CREATE INDEX CMN_missing_index_17856_17855 ON [CM_SP1].[dbo].[Summarizer_ComponentTallys] ([TallyInterval]) INCLUDE ([ComponentDataID], [SiteNumber])
CREATE INDEX CMN_missing_index_12454_12453 ON [CM_SP1].[dbo].[BGB_ResStatus] ([ServerID],[ResourceID]) INCLUDE ([OnlineStatus])
CREATE INDEX CMN_missing_index_19137_19136 ON [CM_SP1].[dbo].[CH_ClientSummary] ([LastMPServerName]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_11702_11701 ON [CM_SP1].[dbo].[BGB_ResTaskHistory] ([TaskID]) INCLUDE ([ResourceID])
CREATE INDEX CMN_missing_index_81_80 ON [CM_SP1].[dbo].[BGB_ResTaskPush] ([Status]) INCLUDE ([ResourceID], [TaskID], [PushID])
CREATE INDEX CMN_missing_index_14923_14922 ON [CM_SP1].[dbo].[DiscItemAgents] ([DiscArchKey], [AgentID],[AgentTime]) INCLUDE ([ItemKey])
CREATE INDEX CMN_missing_index_12244_12243 ON [CM_SP1].[dbo].[TableChangeNotifications] ([Component]) INCLUDE ([Key1])
CREATE INDEX CMN_missing_index_14772_14771 ON [CM_SP1].[dbo].[ClientDeploymentState] ([ItemKey],[LastMessageTime])
CREATE INDEX CMN_missing_index_14774_14773 ON [CM_SP1].[dbo].[ClientDeploymentState] ([ItemKey]) INCLUDE ([RecordID])
CREATE INDEX CMN_missing_index_11393_11392 ON [CM_SP1].[dbo].[PkgServers_L] ([NALPath]) INCLUDE ([Action])
CREATE INDEX CMN_missing_index_21267_21266 ON [CM_SP1].[dbo].[Operating_System_DATA] ([InstallDate00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_431_430 ON [CM_SP1].[dbo].[FolderMembers] ([ContainerNodeID], [IsDeleted]) INCLUDE ([InstanceKey])
CREATE INDEX CMN_missing_index_4186_4185 ON [CM_SP1].[dbo].[BGB_ResStatus] ([OnlineStatus], [ServerID]) INCLUDE ([ResourceID])
CREATE INDEX CMN_missing_index_237_236 ON [msdb].[dbo].[backupset] ([type]) INCLUDE ([backup_finish_date], [database_name])
CREATE INDEX CMN_missing_index_21286_21285 ON [CM_SP1].[dbo].[ClientDeploymentState] ([ItemKey]) INCLUDE ([LastMessageStateID], [ClientVersion], [LastErrorCode])
CREATE INDEX CMN_missing_index_21284_21283 ON [CM_SP1].[dbo].[ADDiscoveryStats] ([StartTime]) INCLUDE ([AgentID], [IsFullSync], [DDRCount], [CompleteTime])
CREATE INDEX CMN_missing_index_15299_15298 ON [CM_SP1].[dbo].[CI_UpdateCIs] ([UpdateSource_ID]) INCLUDE ([CI_ID], [DateRevised], [RevisionNumber])
CREATE INDEX CMN_missing_index_14925_14924 ON [CM_SP1].[dbo].[DiscItemAgents] ([DiscArchKey],[AgentTime]) INCLUDE ([ItemKey], [AgentID])
CREATE INDEX CMN_missing_index_21319_21318 ON [CM_SP1].[dbo].[PC_BIOS_DATA] ([ReleaseDate00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_13876_13875 ON [CM_SP1].[dbo].[EP_DeploymentState] ([DeploymentState])
CREATE INDEX CMN_missing_index_21265_21264 ON [CM_SP1].[dbo].[ClientDeploymentState] ([BaselineType]) INCLUDE ([ItemKey], [SourceType])
CREATE INDEX CMN_missing_index_14776_14775 ON [CM_SP1].[dbo].[ClientDeploymentState] ([SMSID]) INCLUDE ([LastMessageTime])
CREATE INDEX CMN_missing_index_21282_21281 ON [CM_SP1].[dbo].[Update_ScanStatus] ([LastErrorCode])
CREATE INDEX CMN_missing_index_13060_13059 ON [CM_SP1].[dbo].[DBSchema] ([SiteNumber], [ObjectHash])
CREATE INDEX CMN_missing_index_112_111 ON [CM_SP1].[dbo].[BGB_ResTaskPush] ([TaskID], [PushID],[ResourceID])
CREATE INDEX CMN_missing_index_11630_11629 ON [CM_SP1].[dbo].[SoftwarePolicy] ([PkgID], [ProgramName],[ProgramCRC])
CREATE INDEX CMN_missing_index_11633_11632 ON [CM_SP1].[dbo].[SoftwarePolicy] ([OfferID], [PkgID])
CREATE INDEX CMN_missing_index_21263_21262 ON [CM_SP1].[dbo].[ClientDeploymentState] ([BaselineType],[LastMessageStateID]) INCLUDE ([LastMessageParam], [LastErrorCode], [ItemKey], [SourceType])
CREATE INDEX CMN_missing_index_306_305 ON [CM_SP1].[dbo].[SoftwarePolicy] ([OfferID],[OfferCRC])
CREATE INDEX CMN_missing_index_433_432 ON [CM_SP1].[dbo].[FolderMembers] ([IsDeleted]) INCLUDE ([ContainerNodeID], [InstanceKey])
CREATE INDEX CMN_missing_index_21243_21242 ON [CM_SP1].[dbo].[CI_ConfigurationItems] ([IsUserDefined]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_21222_21221 ON [CM_SP1].[dbo].[TaskExecutionStatus] ([ActionTypeName]) INCLUDE ([OfferID], [ItemKey], [ExecutionTime])
CREATE INDEX CMN_missing_index_17239_17238 ON [CM_SP1].[dbo].[DeploymentSummary] ([Type]) INCLUDE ([OfferID], [NumberInstalled], [NumberInProgress], [NumberUnknown], [NumberErrors], [NumberReqsNotMet], [SummarizationTime])
CREATE INDEX CMN_missing_index_11628_11627 ON [CM_SP1].[dbo].[SoftwarePolicy] ([PkgID],[PkgCRC])
CREATE INDEX CMN_missing_index_11637_11636 ON [CM_SP1].[dbo].[SoftwarePolicy] ([PkgID])
CREATE INDEX CMN_missing_index_12158_12157 ON [CM_SP1].[dbo].[SoftwarePolicy] ([OfferID]) INCLUDE ([PolicyID])
CREATE INDEX CMN_missing_index_26737_26736 ON [tempdb].[dbo].[#IndexUsageData_____________________________________________________________________________________________________000000014C8B] ([database_id], [object_id], [index_id]) INCLUDE ([user_seeks], [user_scans], [user_lookups], [user_updates], [last_user_seek], [last_user_scan], [last_user_lookup], [last_user_update], [system_seeks], [system_scans], [system_lookups], [system_updates], [last_system_seek], [last_system_scan], [last_system_lookup], [last_system_update])
CREATE INDEX CMN_missing_index_21224_21223 ON [CM_SP1].[dbo].[EP_DeploymentState] ([ErrorCode]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_26739_26738 ON [tempdb].[dbo].[#IndexUsageData_____________________________________________________________________________________________________000000014C8B] ([database_id]) INCLUDE ([object_id], [index_id], [user_seeks], [user_scans], [user_lookups], [user_updates], [last_user_seek], [last_user_scan], [last_user_lookup], [last_user_update], [system_seeks], [system_scans], [system_lookups], [system_updates], [last_system_seek], [last_system_scan], [last_system_lookup], [last_system_update])
