--SecureBoot Disabled (Daniel)
SELECT
dbo._RES_COLL_WP106CF7.Name AS WKID, 
dbo._RES_COLL_WP106CF7.DeviceOSBuild AS OSBuild,
dbo.v_GS_PC_BIOS.SMBIOSBIOSVersion0 AS SMBIOSVersion, 
dbo.v_GS_PC_BIOS.ReleaseDate0 AS BIOSDate, 
dbo.v_GS_COMPUTER_SYSTEM_PRODUCT.Version0 AS Model
FROM            
dbo._RES_COLL_WP106CF7 INNER JOIN
dbo.v_GS_PC_BIOS ON dbo._RES_COLL_WP106CF7.MachineID = dbo.v_GS_PC_BIOS.ResourceID INNER JOIN
dbo.v_GS_COMPUTER_SYSTEM_PRODUCT ON dbo._RES_COLL_WP106CF7.MachineID = dbo.v_GS_COMPUTER_SYSTEM_PRODUCT.ResourceID
Order by Model

--M910s
SELECT
dbo._RES_COLL_WP105D47.Name AS WKID, 
dbo._RES_COLL_WP105D47.DeviceOSBuild AS OSBuild,
dbo.v_GS_PC_BIOS.SMBIOSBIOSVersion0 AS SMBIOSVersion, 
dbo.v_GS_PC_BIOS.ReleaseDate0 AS BIOSDate, 
dbo.v_GS_COMPUTER_SYSTEM_PRODUCT.Version0 AS Model
FROM            
dbo._RES_COLL_WP105D47 INNER JOIN
dbo.v_GS_PC_BIOS ON dbo._RES_COLL_WP105D47.MachineID = dbo.v_GS_PC_BIOS.ResourceID INNER JOIN
dbo.v_GS_COMPUTER_SYSTEM_PRODUCT ON dbo._RES_COLL_WP105D47.MachineID = dbo.v_GS_COMPUTER_SYSTEM_PRODUCT.ResourceID
ORDER BY SMBIOSVersion