-- PROD table
select *
from tb_Preference
where PreferenceName = 'SCCM Connection String'

-- Restored table
select *
from tb_Preference_restore_from_20210815

/*
update tb_Preference set PreferenceValue = 'SERVER=LOUSQLWPC152A01.rsc.humad.com;DATABASE=CM_WP1;Trusted_Connection=yes;' where PreferenceName = 'SCCM Connection String'

update tb_preference set PreferenceValue = 'http://localhost:8000/ShoppingClientAgent/MachineInfo' where PreferenceName = '1E Client loopback URL'
update tb_preference set PreferenceValue = '10' where PreferenceName = 'Active Directory Integration Interval'
update tb_preference set PreferenceValue = '3' where PreferenceName = 'Active Directory Integration Retries'
update tb_preference set PreferenceValue = '3' where PreferenceName = 'Active Directory Integration Units'
update tb_preference set PreferenceValue = 'LOUAPPWPS1662.rsc.humad.com' where PreferenceName = 'ActiveEfficiency ServerName'
update tb_preference set PreferenceValue = 'mail' where PreferenceName = 'AD Email Field'
update tb_preference set PreferenceValue = 'manager' where PreferenceName = 'AD Manager Account Field'
update tb_preference set PreferenceValue = 'LOUADMWPS03' where PreferenceName = 'AD Server'
update tb_preference set PreferenceValue = '' where PreferenceName = 'AD Trusts'
update tb_preference set PreferenceValue = 'humad\G_1E_Shopping_Admin' where PreferenceName = 'Admin Account'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Admin Console Manages Groups'
update tb_preference set PreferenceValue = 'HumanaAppShop@humana.com' where PreferenceName = 'Admin Email'
update tb_preference set PreferenceValue = 'Administrator' where PreferenceName = 'Admin Name'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'All Approval Applications'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Allow Implicit Access For AD Integration'
update tb_preference set PreferenceValue = '' where PreferenceName = 'Alternative Urls'
update tb_preference set PreferenceValue = 'http://appshop.humana.com/ShoppingAPI' where PreferenceName = 'API Url'
update tb_preference set PreferenceValue = 'Server={0};Database={1};Trusted_Connection=yes;Application Name={2}' where PreferenceName = 'AppClarity Connection String Format'
update tb_preference set PreferenceValue = 'AppClarity' where PreferenceName = 'AppClarity Database'
update tb_preference set PreferenceValue = 'LOUSQLWPS601.rsc.humad.com' where PreferenceName = 'AppClarity Database Server Instance'
update tb_preference set PreferenceValue = 'http://localhost:8335/appclarity/services/integration' where PreferenceName = 'AppClarity Endpoint'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'AppClarity Integration'
update tb_preference set PreferenceValue = 'https://itunes.apple.com/in/genre/ios/id36?mt=8' where PreferenceName = 'Apple app store home url'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Application Index Update duration'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Application Index Update duration unit'
update tb_preference set PreferenceValue = 'App Shop' where PreferenceName = 'Application Name'
update tb_preference set PreferenceValue = 'D:\Program Files (x86)\1E\Shopping\CentralService\WorkFlowIntegration\ApplicationRequestCancelled.vbs' where PreferenceName = 'Application Request Cancelled'
update tb_preference set PreferenceValue = 'D:\Program Files (x86)\1E\Shopping\CentralService\WorkFlowIntegration\ApplicationRequestDeployed.vbs' where PreferenceName = 'Application Request Deployed'
update tb_preference set PreferenceValue = 'D:\Program Files (x86)\1E\Shopping\CentralService\WorkFlowIntegration\Custom-ApplicationRequested.vbs' where PreferenceName = 'Application Requested'
update tb_preference set PreferenceValue = '5' where PreferenceName = 'Application Retry Interval'
update tb_preference set PreferenceValue = '3' where PreferenceName = 'Application Retry Units'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Application Sequence'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Application Wizard Default Enable State'
update tb_preference set PreferenceValue = '' where PreferenceName = 'AppMigration Endpoint'
update tb_preference set PreferenceValue = '0' where PreferenceName = 'AppMigration Mode'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'Approval Applications With Cost'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Approval Escalation Interval'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Approval Escalation Units'
update tb_preference set PreferenceValue = 'D:\Program Files (x86)\1E\Shopping\CentralService\WorkFlowIntegration\Custom-ApprovalProcessCompleted.vbs' where PreferenceName = 'Approval Process Completed'
update tb_preference set PreferenceValue = 'D:\Program Files (x86)\1E\Shopping\CentralService\WorkFlowIntegration\ApprovalUpdate.vbs' where PreferenceName = 'Approval Update'
update tb_preference set PreferenceValue = '14' where PreferenceName = 'Auto Reject Timeout'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'Branch Admins Require Approval'
update tb_preference set PreferenceValue = 'Install%,% Install%' where PreferenceName = 'Bulk Import Tool Install Inclusion Filter'
update tb_preference set PreferenceValue = '%Uninstall%' where PreferenceName = 'Bulk Import Tool Uninstall Inclusion Filter'
update tb_preference set PreferenceValue = 'HUMAD\G_1E_Shopping_Executives_NO_Approval_Required' where PreferenceName = 'Bypass Approval Accounts'
update tb_preference set PreferenceValue = '15' where PreferenceName = 'Cache Duration'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Calculate Most Popular Applications Interval'
update tb_preference set PreferenceValue = '0' where PreferenceName = 'Calculate Most Popular Applications Time'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Calculate Most Popular Applications Units'
update tb_preference set PreferenceValue = 'http://louappwps1662.rsc.humad.com/catalogweb/api' where PreferenceName = 'Catalog Endpoint'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'Centralised Mode'
update tb_preference set PreferenceValue = '-----BEGIN CERTIFICATE-----\nMIIBrTCCAaGgAwIBAgIBATADBgEAMGcxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApD\nYWxpZm9ybmlhMRUwEwYDVQQHDAxTYW50YSBNb25pY2ExETAPBgNVBAoMCE9uZUxv\nZ2luMRkwFwYDVQQDDBBhcHAub25lbG9naW4uY29tMB4XDTEwMDMwOTA5NTgzNFoX\nDTE1MDMwOTA5NTgzNFowZzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3Ju\naWExFTATBgNVBAcMDFNhbnRhIE1vbmljYTERMA8GA1UECgwIT25lTG9naW4xGTAX\nBgNVBAMMEGFwcC5vbmVsb2dpbi5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJ\nAoGBANtmwriqGBbZy5Dwy2CmJEtHEENVPoATCZP3UDESRDQmXy9Q0Kq1lBt+KyV4\nkJNHYAAQ9egLGWQ8/1atkPBye5s9fxROtf8VO3uk/x/X5VSRODIrhFISGmKUnVXa\nUhLFIXkGSCAIVfoR5S2ggdfpINKUWGsWS/lEzLNYMBkURXuVAgMBAAEwAwYBAAMB\nAA==\n-----END CERTIFICATE-----' where PreferenceName = 'Certificate String'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Check Pending Orders Status After'
update tb_preference set PreferenceValue = '90' where PreferenceName = 'Clean Collections or Deployments for Disabled Applications after days'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Comments Always Expanded'
update tb_preference set PreferenceValue = 'LOUAPPWPS1658' where PreferenceName = 'ConfigMgr Central Server Name'
update tb_preference set PreferenceValue = 'WP1' where PreferenceName = 'ConfigMgr Central Site Code'
update tb_preference set PreferenceValue = 'humad\G_MEMCM_ReportAdministrator' where PreferenceName = 'ConfigMgr Database Access Group'
update tb_preference set PreferenceValue = '60' where PreferenceName = 'ConfigMgr Package to AppModel migration check interval'
update tb_preference set PreferenceValue = '' where PreferenceName = 'Console Authentication Client App ID'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Cookie Timeout'
update tb_preference set PreferenceValue = 'en-US' where PreferenceName = 'Currency'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Data Grooming Interval'
update tb_preference set PreferenceValue = '0' where PreferenceName = 'Data Grooming Time'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Data Grooming Units'
update tb_preference set PreferenceValue = 'en' where PreferenceName = 'Default Language For Emails'
update tb_preference set PreferenceValue = '0' where PreferenceName = 'Default View Mode'
update tb_preference set PreferenceValue = 'humad\G_1E_Shopping_Admin' where PreferenceName = 'Deputy Default'
update tb_preference set PreferenceValue = '5' where PreferenceName = 'Email Retry Interval'
update tb_preference set PreferenceValue = '3' where PreferenceName = 'Email Retry Units'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'Enable Mandatory Approval Comments'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Enable Reinstall and License Management'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Enforce Boundaries'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Final Reminder Days'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'Firefox support enabled'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Force Comment For Approval'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'Force Comment For Non-Approval'
update tb_preference set PreferenceValue = '' where PreferenceName = 'Full Admin For RBAC'
update tb_preference set PreferenceValue = 'humad\G_1E_Shopping_DB_Admin' where PreferenceName = 'Full Database Access Group'
update tb_preference set PreferenceValue = 'HUMAD\G_1E_Shopping_Licensing_Manager' where PreferenceName = 'Global License Manager Account'
update tb_preference set PreferenceValue = '' where PreferenceName = 'Global License Manager Email'
update tb_preference set PreferenceValue = 'https://play.google.com/store/apps' where PreferenceName = 'Google app store home url'
update tb_preference set PreferenceValue = '100' where PreferenceName = 'Graph API Batch Size'
update tb_preference set PreferenceValue = '40' where PreferenceName = 'Help Desk Cost'
update tb_preference set PreferenceValue = '30' where PreferenceName = 'Help Desk Time'
update tb_preference set PreferenceValue = 'D:\Program Files (x86)\1E\Shopping\CentralService\WorkFlowIntegration\InstallationProcessCompleted.vbs' where PreferenceName = 'Installation Process Completed'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Integration Mode'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'Intune Integration Enabled'
update tb_preference set PreferenceValue = '5' where PreferenceName = 'Intune Order Status Processor Interval'
update tb_preference set PreferenceValue = '3' where PreferenceName = 'Intune Order Status Processor Interval Unit'
update tb_preference set PreferenceValue = '0' where PreferenceName = 'Last Legacy Completed Order Id'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'LDAP Over SSL/TLS Enabled'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'License Dependency'
update tb_preference set PreferenceValue = 'humad\G_1E_Shopping_DB_Limited' where PreferenceName = 'Limited Database Access Group'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'Loopback exemption enabled'
update tb_preference set PreferenceValue = 'HTML' where PreferenceName = 'Mail Format'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'Make OSD Confirm Box Visible'
update tb_preference set PreferenceValue = '168' where PreferenceName = 'Maximum Approval Hours'
update tb_preference set PreferenceValue = '72' where PreferenceName = 'Maximum Branch Approval Hours'
update tb_preference set PreferenceValue = '30' where PreferenceName = 'Maximum Days In Basket'
update tb_preference set PreferenceValue = '3' where PreferenceName = 'Maximum Email Retries'
update tb_preference set PreferenceValue = '100' where PreferenceName = 'Maximum Machines Count'
update tb_preference set PreferenceValue = '3' where PreferenceName = 'Maximum Workflow Retries'
update tb_preference set PreferenceValue = '180' where PreferenceName = 'Most Popular Applications Day Range'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'New UI Enabled'
update tb_preference set PreferenceValue = '500' where PreferenceName = 'Number Of Events To Display'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Number Of Receiver Order Processing Threads'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Number of workflow threads'
update tb_preference set PreferenceValue = '15' where PreferenceName = 'OS Deployment Calendar Reminder Time'
update tb_preference set PreferenceValue = '3' where PreferenceName = 'OS Deployment Calendar Schedule Time Interval'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'OS Deployment Workflow Integration Enabled'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'OS Filtering Enabled'
update tb_preference set PreferenceValue = '720' where PreferenceName = 'OS Filtering Sync Period'
update tb_preference set PreferenceValue = '5' where PreferenceName = 'OS Filtering Thread Sleep Interval'
update tb_preference set PreferenceValue = '2' where PreferenceName = 'OSD Completed Machine Discovery Interval'
update tb_preference set PreferenceValue = '48' where PreferenceName = 'OSD Completed Machine Discovery Timeout Hours'
update tb_preference set PreferenceValue = '3' where PreferenceName = 'OSD Completed Machine Discovery Units'
update tb_preference set PreferenceValue = 'Software\1E\ShoppingCentral' where PreferenceName = 'Our Software Path'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Overdue Pending Orders Interval'
update tb_preference set PreferenceValue = '72' where PreferenceName = 'Overdue Pending Orders Time Out'
update tb_preference set PreferenceValue = '2' where PreferenceName = 'Overdue Pending Orders Units'
update tb_preference set PreferenceValue = '10' where PreferenceName = 'Paged Items Applications Page'
update tb_preference set PreferenceValue = '10' where PreferenceName = 'Paged Items Basket Page'
update tb_preference set PreferenceValue = '10' where PreferenceName = 'Paged Items Orders Page'
update tb_preference set PreferenceValue = '10' where PreferenceName = 'Pending Requests Interval Seconds'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Query SCCM Data From Server'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'RBAC Support Enabled'
update tb_preference set PreferenceValue = 'HUMAD\G_1E_Shopping_Receivers' where PreferenceName = 'Receiver Account'
update tb_preference set PreferenceValue = '10' where PreferenceName = 'Receiver Processing Batch Size'
update tb_preference set PreferenceValue = '10' where PreferenceName = 'Recommended Item Install Delay'
update tb_preference set PreferenceValue = '' where PreferenceName = 'Recommended Item User Account'
update tb_preference set PreferenceValue = '99999' where PreferenceName = 'Records Purge Days'
update tb_preference set PreferenceValue = '5' where PreferenceName = 'Reminder Days'
update tb_preference set PreferenceValue = '90' where PreferenceName = 'Rental Extension Default Days'
update tb_preference set PreferenceValue = '120' where PreferenceName = 'Rental Extension Maximum Days'
update tb_preference set PreferenceValue = '60' where PreferenceName = 'Rental Extension Minimum Days'
update tb_preference set PreferenceValue = 'HUMAD\G_1E_Shopping_Reporting_Manager' where PreferenceName = 'Reports Account'
update tb_preference set PreferenceValue = '' where PreferenceName = 'Restricted AD Groups'
update tb_preference set PreferenceValue = 'C:\ProgramData\1E\ShoppingCentral\Retry\' where PreferenceName = 'Retry Path'
update tb_preference set PreferenceValue = '24' where PreferenceName = 'Retry Status Update For Failed Installations for Time Interval'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'SCCM Available'
update tb_preference set PreferenceValue = 'SERVER=LOUSQLWPS606.rsc.humad.com;DATABASE=CM_WP1;Trusted_Connection=yes;' where PreferenceName = 'SCCM Connection String'
update tb_preference set PreferenceValue = '' where PreferenceName = 'SCCM Old Connection String'
update tb_preference set PreferenceValue = '10' where PreferenceName = 'SCCM Sync Batch Size'
update tb_preference set PreferenceValue = '5.00.9040.1000' where PreferenceName = 'SCCM Version'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Scheduled Uninstall Interval'
update tb_preference set PreferenceValue = '2' where PreferenceName = 'Scheduled Uninstall Units'
update tb_preference set PreferenceValue = 'C:\ProgramData\1E\ShoppingCentral\temp\' where PreferenceName = 'Script Temp Path'
update tb_preference set PreferenceValue = '10' where PreferenceName = 'Script Timeout Seconds'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'Send Email When Application Deployed'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Send OS Deployment Confirmation Email'
update tb_preference set PreferenceValue = '24' where PreferenceName = 'Send OS Deployment Imminent Email'
update tb_preference set PreferenceValue = '7' where PreferenceName = 'Send OS Deployment Reminder Email'
update tb_preference set PreferenceValue = '50' where PreferenceName = 'Send OS Migration Cancelled Email Interval'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Send OS Migration Cancelled Email Units'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Send OS Migration Imminent Email Interval'
update tb_preference set PreferenceValue = '2' where PreferenceName = 'Send OS Migration Imminent Email Units'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Send OS Migration Reminder Email Interval'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Send OS Migration Reminder Email Units'
update tb_preference set PreferenceValue = 'humad\1E_ShoppingSrv' where PreferenceName = 'Service Account'
update tb_preference set PreferenceValue = '' where PreferenceName = 'Service Authentication Client App ID'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Show Admin Tab'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Show My Software Link'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Show New/Popular Items'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Show Preference Link'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'Show Savings To Date'
update tb_preference set PreferenceValue = 'oF70FqC5FciMGsr36X3x0Q==' where PreferenceName = 'SLA Platform Password'
update tb_preference set PreferenceValue = '' where PreferenceName = 'SLA Platform Username'
update tb_preference set PreferenceValue = 'pobox.humana.com' where PreferenceName = 'SMTP Server'
update tb_preference set PreferenceValue = '' where PreferenceName = 'SSO Identity Header'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Sync Machines and Users From Active Efficiency'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'Sync Machines From Old Sccm'
update tb_preference set PreferenceValue = '' where PreferenceName = 'Sync WSA Orders Account'
update tb_preference set PreferenceValue = '' where PreferenceName = 'Tenant Id'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Use Extended Table For OSD Reinstall Screen'
update tb_preference set PreferenceValue = 'TRUE' where PreferenceName = 'Use Global Catalog'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'Use Login Language'
update tb_preference set PreferenceValue = '0' where PreferenceName = 'User Splash Message'
update tb_preference set PreferenceValue = '12' where PreferenceName = 'Users and Machines, AD Sync Interval'
update tb_preference set PreferenceValue = '10' where PreferenceName = 'Users and Machines, AD Sync Sleep Duration'
update tb_preference set PreferenceValue = '2' where PreferenceName = 'Users and Machines, AD Sync Units'
update tb_preference set PreferenceValue = 'http://appshop.humana.com/Shopping' where PreferenceName = 'Web URL'
update tb_preference set PreferenceValue = 'http://www.windowsphone.com/en-in/store/' where PreferenceName = 'Windows app store home Url'
update tb_preference set PreferenceValue = '1' where PreferenceName = 'Workflow Integration Mode'
update tb_preference set PreferenceValue = 'FALSE' where PreferenceName = 'WQL Support Enabled'
update tb_preference set PreferenceValue = '%ONEDRIVE%|%PROGRAMFILES%|%PROGRAMFILES(X86)%|%PROGRAMW6432%|%PUBLIC%|%SYSTEMROOT%|%PROGRAMDATA%|%SystemDrive%\Users' where PreferenceName = 'WSA System Folder Exclusions'


*/