With ARPData as (
select distinct displayname0, case
	   WHEN DisplayName0 like 'Security Update for%' THEN 'Patch'
	   WHEN DisplayName0 like 'Update for%' THEN 'Patch'
	   WHEN DisplayName0 like 'Definition Update for%' THEN 'Patch'
	   WHEN DisplayName0 like 'Service Pack%' THEN 'Patch'
	   WHEN DisplayName0 like 'Hotfix for%' THEN 'Patch'
	   WHEN DisplayName0 like 'Reliability update for%' THEN 'Patch'
	   WHEN DisplayName0 = '1E Agent' THEN 'Base Image'
	   WHEN DisplayName0 = '1E NomadBranch x64' THEN 'Base Image'
	   WHEN DisplayName0 = '1E Shopping Agent' THEN 'Base Image'
	   WHEN DisplayName0 = '1E Shopping Client Identity' THEN 'Base Image'
	   WHEN DisplayName0 = 'Adobe PDF iFilter 11 for 64-bit platforms' THEN 'Base Image'
	   WHEN DisplayName0 LIKE 'Adobe Flash Player%' THEN 'Base Image'
	   WHEN DisplayName0 = 'BeyondTrust Certificate Installer' THEN 'Base Image'
	   WHEN DisplayName0 = 'BeyondTrust PowerBroker Desktops Client for Windows' THEN 'Base Image'
	   WHEN DisplayName0 = 'RightFax Print Processor x64' THEN 'Base Image'
	   WHEN DisplayName0 = 'RightFax Product Suite - Client' THEN 'Base Image'
	   WHEN DisplayName0 = 'Cisco WebEx Meeting Center' THEN 'Base Image'
	   WHEN DisplayName0 like 'Citrix Receiver%' THEN 'Base Image'
	   WHEN DisplayName0 = 'Online Plug-in' THEN 'Base Image'
	   WHEN DisplayName0 = 'xagt' THEN 'Base Image'
	   WHEN DisplayName0 = 'Advanced Tiff Editor' THEN 'Base Image'
	   WHEN DisplayName0 = 'Hitachi ID Password Manager Local Reset Extension' THEN 'Base Image'
	   WHEN DisplayName0 = 'Hitachi ID Password Manager Local SKA' THEN 'Base Image'
	   WHEN DisplayName0 = 'Fontsmith Condensed FS Me or Humana Sans for PC 3' THEN 'Base Image'
	   WHEN DisplayName0 = 'Workstation ID 7.0.6' THEN 'Base Image'
	   WHEN DisplayName0 = 'Fontsmith Humana SANS font 1' THEN 'Base Image'
	   WHEN DisplayName0 = 'Humana Outlook 2010 Secure Mail Add-In' THEN 'Base Image'
	   WHEN DisplayName0 = 'IBM Host On-Demand EHLLAPI Bridge 3.0.5' THEN 'Base Image'
	   WHEN DisplayName0 = 'ISAM ESSO AccessAgent' THEN 'Base Image'
	   WHEN DisplayName0 = 'Intel(R) Processor Graphics' THEN 'Base Image'
	   WHEN DisplayName0 = 'McAfee Agent' THEN 'Base Image'
	   WHEN DisplayName0 = 'McAfee VirusScan Enterprise' THEN 'Base Image'
	   WHEN DisplayName0 = 'Configuration Manager Client' THEN 'Base Image'
	   WHEN DisplayName0 = 'Local Administrator Password Solution' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft Access MUI (English) 2016' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft Application Virtualization Desktop Client' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft Excel MUI (English) 2016' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft InfoPath 2013' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft InfoPath MUI (English) 2013' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft InfoPath MUI (English) 2016' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft Lync 2013' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft Lync MUI (English) 2013' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft Lync Tabbed Conversations' THEN 'Base Image'
	   WHEN DisplayName0 like 'Microsoft Office%' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft OneNote MUI (English) 2016' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft Outlook MUI (English) 2016' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft PowerPoint MUI (English) 2016' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft Publisher MUI (English) 2016' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft Silverlight' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft Skype for Business 2016' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft Skype for Business MUI (English) 2016' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft SQL Server Compact 3.5 SP2 ENU' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft SQL Server Compact 3.5 SP2 x64 ENU' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft SQL Server Compact 4.0 SP1 x64 ENU' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft Visio Viewer 2013' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft Visio Viewer 2016' THEN 'Base Image'
	   WHEN DisplayName0 like 'Microsoft Visual C++%Redistributable%' THEN 'Base Image'
	   WHEN DisplayName0 = 'Microsoft Visual Studio 2010 Tools for Office Runtime (x64)' THEN 'Base Image'
	   WHEN DisplayName0 like 'MSXML 4.0 SP3 Parser%' THEN 'Base Image'
	   WHEN DisplayName0 = 'Skype for Business 2016' THEN 'Base Image'
	   WHEN DisplayName0 = 'NVIDIA Display Control Panel' THEN 'Base Image'
	   WHEN DisplayName0 = 'NVIDIA Drivers' THEN 'Base Image'
	   WHEN DisplayName0 = 'Realtek High Definition Audio Driver' THEN 'Base Image'
	   WHEN DisplayName0 = 'Digital Guardian Agent' THEN 'Base Image'
	   WHEN DisplayName0 = 'VoiceRite Desktop Client' THEN 'Base Image'
	   WHEN DisplayName0 = 'ThinkRite Voice Desktop Client 4.0.15' THEN 'Base Image'
	   WHEN DisplayName0 like 'SecureDoc Disk Encryption%' THEN 'Base Image'
	   WHEN DisplayName0 = 'Humana Perfect Service Wallpapers' THEN 'Base Image'
	   WHEN DisplayName0 like 'Java(TM) 6 Update 43%' THEN 'Base Image'
	   WHEN DisplayName0 like 'Java 7 Update%' THEN 'Base Image'
	   WHEN DisplayName0 like 'Java 8 Update%' THEN 'Base Image'
	   else 'Business'
	   end [Category]
	   from v_Add_Remove_Programs)
select distinct arp.Publisher0 [Mfg], arp.DisplayName0 [Product], arp.Version0 [Version], arpd.Category, count(*) [Count]
from v_r_system_valid sys join
	 v_Add_Remove_Programs ARP on sys.ResourceID = arp.ResourceID join
	 ARPData ARPD on ARP.displayname0 = arpd.displayname0
where sys.Netbios_Name0 in (@Machines) and ARPD.Category in (@Category)
group by arp.Publisher0, arp.DisplayName0, arp.Version0, arpd.Category
order by arp.Publisher0, arp.DisplayName0, arp.Version0, arpd.Category