#Get Nomad cache path from the registry
$LocalCachePath = [string](Get-ItemProperty -Path Registry::HKEY_LOCAL_MACHINE\SOFTWARE\1E\NomadBranch -Name LocalCachePath -ErrorAction Ignore).LocalCachePath

#Loop through the .LsZ files and return any that were generated by a QA DP.
$AllLSZ = Get-ChildItem -Path $LocalCachePath -Filter *.LsZ 
ForEach ($File in $AllLSZ) {
    If (Get-Content -Path $file.FullName | Select-String 'Generated by "LOUAPPWQ') {
        Write-Output "$file"
        }
        
    }
