$LocalCachePath = [string](Get-ItemProperty -Path Registry::HKEY_LOCAL_MACHINE\SOFTWARE\1E\NomadBranch -Name LocalCachePath -ErrorAction Ignore).LocalCachePath

#Loop through the .LsZ files and return any that were generated by a QA DP.
$AllLSZ = Get-ChildItem -Path $LocalCachePath -Filter *.LsZ 
ForEach ($File in $AllLSZ) {
    If (Get-Content -Path $file.FullName | Select-String 'Generated by "LOUAPPWQ') {
        $File.BaseName | Out-File -FilePath "C:\temp\RemovedLsZfiles.txt" -Append
        $PkgInfo = $File.Basename -split '_'
        $PkgID = $PkgInfo[0]
        $Arg_PkgID = "-DeletePkg=$PkgID"
        $PkgVer = $PkgInfo[1]
        $Arg_PkgVer = "-PkgVer=$PkgVer"
        $startProcessSplat = @{
            PassThru     = $true
            FilePath     = "$env:ProgramFiles\1E\NomadBranch\CacheCleaner.exe"
            ArgumentList = $Arg_PkgID, $Arg_PkgVer
            WindowStyle  = 'Hidden'
            Wait         = $true
        }
        Start-Process @startProcessSplat
    }
}