CREATE INDEX CMN_missing_index_943_942 ON [CM_WQ1].[dbo].[Group_User_Relationship] ([Group_ObjectGUID]) INCLUDE ([User_ObjectGUID], [GroupType])
CREATE INDEX CMN_missing_index_937_936 ON [CM_WQ1].[dbo].[Group_User_Relationship] ([Group_ObjectGUID], [User_ObjectGUID]) INCLUDE ([GroupType])
CREATE INDEX CMN_missing_index_933_932 ON [CM_WQ1].[dbo].[Group_User_Relationship] ([Group_ObjectGUID]) INCLUDE ([AgentID], [User_ObjectGUID], [GroupType], [LastRefreshTime])
CREATE INDEX CMN_missing_index_939_938 ON [CM_WQ1].[dbo].[Group_System_Relationship] ([Group_ObjectGUID], [System_ObjectGUID]) INCLUDE ([GroupType])
CREATE INDEX CMN_missing_index_945_944 ON [CM_WQ1].[dbo].[Group_System_Relationship] ([Group_ObjectGUID]) INCLUDE ([System_ObjectGUID], [GroupType])
CREATE INDEX CMN_missing_index_927_926 ON [CM_WQ1].[dbo].[Group_System_Relationship] ([Group_ObjectGUID]) INCLUDE ([AgentID], [System_ObjectGUID], [GroupType], [LastRefreshTime])
CREATE INDEX CMN_missing_index_540649_540648 ON [CM_WQ1].[dbo].[System_DISC] ([ManagementAuthority]) INCLUDE ([SMS_Unique_Identifier0])
CREATE INDEX CMN_missing_index_542491_542490 ON [CM_WQ1].[dbo].[Flat_Group_User_Relationship_Path] ([ParentGroup]) INCLUDE ([ChildUser], [IsSecureRelationship])
CREATE INDEX CMN_missing_index_941_940 ON [CM_WQ1].[dbo].[Group_Group_Relationship] ([ParentGroup_ObjectGUID])
CREATE INDEX CMN_missing_index_542495_542494 ON [CM_WQ1].[dbo].[Flat_Group_User_Relationship] ([Group_ObjectGUID], [SiteCode]) INCLUDE ([User_ObjectGUID])
CREATE INDEX CMN_missing_index_686_685 ON [CM_WQ1].[dbo].[User_DISC] ([Object_GUID0]) INCLUDE ([ItemKey], [SID0], [Distinguished_Name0])
CREATE INDEX CMN_missing_index_31_30 ON [CM_WQ1].[dbo].[SoftwarePolicy] ([PkgID], [ProgramName],[ProgramCRC])
CREATE INDEX CMN_missing_index_683_682 ON [CM_WQ1].[dbo].[DiscItemAgents] ([AgentID]) INCLUDE ([ItemKey], [AgentTime])
CREATE INDEX CMN_missing_index_542497_542496 ON [CM_WQ1].[dbo].[Flat_Group_User_Relationship] ([SiteCode]) INCLUDE ([Group_ObjectGUID], [User_ObjectGUID])
CREATE INDEX CMN_missing_index_239_238 ON [CM_WQ1].[dbo].[SoftwarePolicy] ([OfferID], [PkgID])
CREATE INDEX CMN_missing_index_688_687 ON [CM_WQ1].[dbo].[DiscScope_ImmediateGroup] ([Group_ObjectGUID])
CREATE INDEX CMN_missing_index_542499_542498 ON [CM_WQ1].[dbo].[Flat_Group_User_Relationship_NS] ([SiteCode]) INCLUDE ([Group_ObjectGUID], [User_ObjectGUID])
CREATE INDEX CMN_missing_index_29_28 ON [CM_WQ1].[dbo].[SoftwarePolicy] ([PkgID],[PkgCRC])
CREATE INDEX CMN_missing_index_242_241 ON [CM_WQ1].[dbo].[SoftwarePolicy] ([PkgID])
CREATE INDEX CMN_missing_index_690_689 ON [CM_WQ1].[dbo].[SoftwarePolicy] ([OfferID], [PkgID]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_694_693 ON [CM_WQ1].[dbo].[ActiveDirectoryObjectInfo] ([SiteCode], [LastRefreshTime]) INCLUDE ([ObjectGUID])
CREATE INDEX CMN_missing_index_702_701 ON [CM_WQ1].[dbo].[DeploymentSummary] ([OfferID])
CREATE INDEX CMN_missing_index_555622_555621 ON [CM_WQ1].[dbo].[Flat_Group_User_Relationship_NS] ([Group_ObjectGUID], [SiteCode]) INCLUDE ([User_ObjectGUID])
CREATE INDEX CMN_missing_index_206_205 ON [CM_WQ1].[dbo].[SoftwarePolicy] ([PkgID], [ProgramName], [ParentPolicyID],[OfferID])
CREATE INDEX CMN_missing_index_2298_2297 ON [CM_WQ1].[dbo].[ActiveDirectoryObjectInfo] ([Name])
CREATE INDEX CMN_missing_index_692_691 ON [CM_WQ1].[dbo].[Flat_Group_Group_Relationship] ([ChildGroup_ObjectGUID]) INCLUDE ([ParentGroup_ObjectGUID])
CREATE INDEX CMN_missing_index_542493_542492 ON [CM_WQ1].[dbo].[Flat_Group_System_Relationship_Path] ([ParentGroup]) INCLUDE ([ChildSystem], [IsSecureRelationship])
CREATE INDEX CMN_missing_index_700_699 ON [CM_WQ1].[dbo].[SoftwarePolicy] ([OfferID], [ParentPolicyID])
CREATE INDEX CMN_missing_index_805_804 ON [CM_WQ1].[dbo].[FolderMembers] ([ContainerNodeID], [IsDeleted])
CREATE INDEX CMN_missing_index_704_703 ON [CM_WQ1].[dbo].[ResPolicyMap] ([IsTombstoned]) INCLUDE ([MachineID], [PADBID])
CREATE INDEX CMN_missing_index_2_1 ON [CM_WQ1].[dbo].[SoftwarePolicy] ([PADBID]) INCLUDE ([PkgID], [ProgramName])
CREATE INDEX CMN_missing_index_4903_4902 ON [CM_WQ1].[dbo].[Flat_Group_System_Relationship] ([Group_ObjectGUID], [SiteCode]) INCLUDE ([System_ObjectGUID])
CREATE INDEX CMN_missing_index_766_765 ON [CM_WQ1].[dbo].[AttributeMap] ([GroupKey], [IsKey])
CREATE INDEX CMN_missing_index_712_711 ON [CM_WQ1].[dbo].[ActiveDirectoryObjectInfo] ([CName]) INCLUDE ([ObjectGUID], [SiteCode], [LastRefreshTime])
CREATE INDEX CMN_missing_index_768_767 ON [CM_WQ1].[dbo].[AttributeMap] ([IsKey]) INCLUDE ([GroupKey])
CREATE INDEX CMN_missing_index_4_3 ON [CM_WQ1].[dbo].[PkgServers_L] ([NALPath])
CREATE INDEX CMN_missing_index_514419_514418 ON [DBATools].[Paramain].[ObjectGroup] ([SPID]) INCLUDE ([ObjectGroupID])
CREATE INDEX CMN_missing_index_807_806 ON [CM_WQ1].[dbo].[RBAC_InstancePermissions] ([ObjectTypeID]) INCLUDE ([AdminID], [ObjectKey], [GrantedOperations])
CREATE INDEX CMN_missing_index_809_808 ON [CM_WQ1].[dbo].[CI_ConfigurationItems] ([CIType_ID], [IsTombstoned]) INCLUDE ([CI_ID], [CI_UniqueID])
CREATE INDEX CMN_missing_index_47999_47998 ON [CM_WQ1].[dbo].[Update_ComplianceStatus] ([EnforcementSource],[LastEnforcementMessageID], [LastEnforcementMessageTime]) INCLUDE ([CI_ID], [MachineID])
CREATE INDEX CMN_missing_index_24_23 ON [CM_WQ1].[dbo].[SoftwarePolicy] ([OfferID])
CREATE INDEX CMN_missing_index_811_810 ON [CM_WQ1].[dbo].[CI_ConfigurationItems] ([IsTombstoned]) INCLUDE ([CI_ID], [CI_UniqueID], [CIType_ID])
CREATE INDEX CMN_missing_index_706_705 ON [CM_WQ1].[dbo].[Collection_Rules] ([RuleType], [ArchitectureKey],[MachineID]) INCLUDE ([CollectionID])
CREATE INDEX CMN_missing_index_230_229 ON [CM_WQ1].[dbo].[PolicyAssignment] ([PolicyAssignmentID])
CREATE INDEX CMN_missing_index_1214_1213 ON [CM_WQ1].[dbo].[Flat_Group_Group_Relationship_Path] ([ParentGroup]) INCLUDE ([ChildGroup], [IsSecureRelationship])
CREATE INDEX CMN_missing_index_708_707 ON [CM_WQ1].[dbo].[Collection_Rules] ([RuleType],[MachineID]) INCLUDE ([CollectionID], [ArchitectureKey])
CREATE INDEX CMN_missing_index_696_695 ON [CM_WQ1].[dbo].[DeploymentSummary] ([AssignmentID]) INCLUDE ([SummarizationTime])
CREATE INDEX CMN_missing_index_749_748 ON [CM_WQ1].[dbo].[DeploymentSummary] ([Type]) INCLUDE ([SiteNumber], [CollectionID], [OfferID], [AssignmentID], [SummaryType])
CREATE INDEX CMN_missing_index_710_709 ON [CM_WQ1].[dbo].[Collection_Rules] ([RuleType]) INCLUDE ([CollectionID], [ReferencedCollectionID])
CREATE INDEX CMN_missing_index_821_820 ON [CM_WQ1].[dbo].[DeploymentSummary] ([OfferID],[Type]) INCLUDE ([NumberInstalled], [NumberInProgress], [NumberUnknown], [NumberErrors], [NumberReqsNotMet], [SummarizationTime])
CREATE INDEX CMN_missing_index_22_21 ON [CM_WQ1].[dbo].[SoftwarePolicy] ([ParentPolicyID],[OfferID]) INCLUDE ([PolicyID], [PkgID], [ProgramName])
CREATE INDEX CMN_missing_index_753_752 ON [CM_WQ1].[dbo].[CI_ConfigurationItems] ([CIType_ID], [IsHidden]) INCLUDE ([CI_ID], [ModelId], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_755_754 ON [CM_WQ1].[dbo].[CI_ConfigurationItems] ([IsHidden]) INCLUDE ([CI_ID], [ModelId], [CIType_ID], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_39527_39526 ON [CM_WQ1].[dbo].[Add_Remove_Programs_DATA] ([DisplayName00])
CREATE INDEX CMN_missing_index_27_26 ON [CM_WQ1].[dbo].[PkgPrograms_G] ([DependentProgram]) INCLUDE ([PkgID], [Name])
CREATE INDEX CMN_missing_index_823_822 ON [CM_WQ1].[dbo].[DeploymentSummary] ([Type]) INCLUDE ([OfferID], [NumberInstalled], [NumberInProgress], [NumberUnknown], [NumberErrors], [NumberReqsNotMet], [SummarizationTime])
CREATE INDEX CMN_missing_index_14_13 ON [CM_WQ1].[dbo].[ContentDistributionNotification] ([DPID]) INCLUDE ([DistributionID])
CREATE INDEX CMN_missing_index_15323_15322 ON [CM_WQ1].[dbo].[SCCM_Audit] ([ChangeTime]) INCLUDE ([ID])
CREATE INDEX CMN_missing_index_747_746 ON [CM_WQ1].[dbo].[DeploymentSummary] ([Type]) INCLUDE ([SiteNumber], [CollectionID], [OfferID], [ModelID], [AssignmentID], [DeploymentTime], [SummaryType])
CREATE INDEX CMN_missing_index_267962_267961 ON [CM_WQ1].[dbo].[Update_ComplianceStatus] ([MachineID],[LastStatusCheckTime], [LastEnforcementMessageTime]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_698_697 ON [CM_WQ1].[dbo].[DeploymentSummary] ([OfferID]) INCLUDE ([SummarizationTime])
CREATE INDEX CMN_missing_index_166791_166790 ON [CM_WQ1].[dbo].[Update_ComplianceStatus] ([MachineID]) INCLUDE ([CI_ID], [Status], [LastStatusCheckTime], [LastEnforcementMessageID], [rowversion])
CREATE INDEX CMN_missing_index_818_817 ON [CM_WQ1].[dbo].[DeploymentSummary] ([Type]) INCLUDE ([SiteNumber], [CollectionID], [OfferID], [ModelID], [AssignmentID], [Description], [DeploymentTime], [ModificationTime], [DeploymentIntent], [NumberInstalled], [NumberInProgress], [NumberUnknown], [NumberErrors], [NumberReqsNotMet], [SummarizationTime], [SummaryType])
CREATE INDEX CMN_missing_index_514430_514429 ON [DBATools].[Paramain].[CommandLog] ([DatabaseName], [SchemaName], [ObjectName], [ObjectType], [EndTime]) INCLUDE ([conversation_handle])
CREATE INDEX CMN_missing_index_530452_530451 ON [CM_WQ1].[dbo].[LU_SoftwareCode] ([SoftwareCode]) INCLUDE ([SoftwareID])
CREATE INDEX CMN_missing_index_18_17 ON [CM_WQ1].[dbo].[CI_ConfigurationItems] ([IsTombstoned], [IsExpired], [SourceSite],[CIType_ID]) INCLUDE ([CI_ID], [DateCreated], [DateLastModified])
CREATE INDEX CMN_missing_index_757_756 ON [CM_WQ1].[dbo].[CI_ConfigurationItems] ([IsLatest]) INCLUDE ([CI_ID], [ModelId], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_530450_530449 ON [CM_WQ1].[dbo].[LU_SoftwareHash] ([SourceSite],[LastUpdated])
CREATE INDEX CMN_missing_index_39529_39528 ON [CM_WQ1].[dbo].[Add_Remove_Programs_64_DATA] ([DisplayName00])
CREATE INDEX CMN_missing_index_540851_540850 ON [CM_WQ1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([SMS_Unique_Identifier0], [Creation_Date0])
CREATE INDEX CMN_missing_index_10_9 ON [CM_WQ1].[dbo].[PkgStatus_L] ([Type], [PkgServer]) INCLUDE ([ID])
CREATE INDEX CMN_missing_index_788_787 ON [ReportServer].[dbo].[Catalog] ([Type]) INCLUDE ([ParentID])
CREATE INDEX CMN_missing_index_236_235 ON [CM_WQ1].[dbo].[PolicyAssignment] ([PolicyAssignmentID]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_548319_548318 ON [CM_WQ1].[dbo].[CI_ConfigurationItems] ([IsTombstoned]) INCLUDE ([ConfigurationFlags])
CREATE INDEX CMN_missing_index_726_725 ON [CM_WQ1].[dbo].[FolderMembers] ([ContainerNodeID], [IsDeleted]) INCLUDE ([InstanceKey])
CREATE INDEX CMN_missing_index_790_789 ON [ReportServer].[dbo].[Catalog] ([Type]) INCLUDE ([ItemID], [Path], [ParentID], [Description], [Hidden], [CreationDate])
CREATE INDEX CMN_missing_index_12_11 ON [CM_WQ1].[dbo].[PkgStatus_L] ([Type]) INCLUDE ([ID], [PkgServer])
CREATE INDEX CMN_missing_index_232_231 ON [CM_WQ1].[dbo].[PolicyAssignment] ([IsTombstoned]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_234_233 ON [CM_WQ1].[dbo].[PolicyAssignment] ([IsTombstoned]) INCLUDE ([PADBID], [PolicyAssignmentID])
CREATE INDEX CMN_missing_index_530422_530421 ON [CM_WQ1].[dbo].[DiscItemAgents] ([DiscArchKey]) INCLUDE ([ItemKey], [AgentTime])
CREATE INDEX CMN_missing_index_540647_540646 ON [CM_WQ1].[dbo].[StatusMessages] ([DeleteTime]) INCLUDE ([RecordID])
CREATE INDEX CMN_missing_index_720_719 ON [CM_WQ1].[dbo].[CollectionNotifications] ([TableName],[RecordID], [MachineID])
CREATE INDEX CMN_missing_index_280007_280006 ON [CM_WQ1].[dbo].[CI_ConfigurationItems] ([CIType_ID]) INCLUDE ([CI_ID], [ModelId], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_540657_540656 ON [CM_WQ1].[dbo].[CollectionMembers] ([SiteID],[ArchitectureKey], [SMSID]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_968_967 ON [CM_WQ1].[dbo].[PkgStatus_L] ([Type]) INCLUDE ([ID], [PkgServer], [Status], [SourceVersion])
CREATE INDEX CMN_missing_index_1082_1081 ON [CM_WQ1].[dbo].[SoftwarePolicy] ([OfferID], [ParentPolicyID]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_548311_548310 ON [CM_WQ1].[dbo].[User_DISC] ([AADTenantID]) INCLUDE ([AADUserID])
CREATE INDEX CMN_missing_index_843_842 ON [CM_WQ1].[dbo].[SoftwarePolicy] ([OfferID]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_728_727 ON [CM_WQ1].[dbo].[Folders] ([ObjectType]) INCLUDE ([ContainerNodeID])
CREATE INDEX CMN_missing_index_730_729 ON [CM_WQ1].[dbo].[FolderMembers] ([IsDeleted]) INCLUDE ([ContainerNodeID], [InstanceKey])
CREATE INDEX CMN_missing_index_1084_1083 ON [CM_WQ1].[dbo].[SoftwarePolicy] ([ParentPolicyID]) INCLUDE ([PADBID], [OfferID])
CREATE INDEX CMN_missing_index_1020_1019 ON [CM_WQ1].[dbo].[Folders] ([ObjectType], [SearchFolder], [IsDeleted]) INCLUDE ([ContainerNodeID], [Name], [ParentContainerNodeID], [FolderFlags], [SourceSite], [FolderGuid])
CREATE INDEX CMN_missing_index_850_849 ON [CM_WQ1].[dbo].[SoftwarePolicy] ([OfferID],[OfferCRC])
CREATE INDEX CMN_missing_index_5109_5108 ON [CM_WQ1].[dbo].[CI_ConfigurationItems] ([IsTombstoned]) INCLUDE ([CI_UniqueID])
CREATE INDEX CMN_missing_index_548291_548290 ON [CM_WQ1].[dbo].[System_DISC] ([Client_Type0]) INCLUDE ([ItemKey], [DiscArchKey], [Decommissioned0])
CREATE INDEX CMN_missing_index_548299_548298 ON [CM_WQ1].[dbo].[System_DISC] ([AADDeviceID]) INCLUDE ([Client0])
CREATE INDEX CMN_missing_index_548297_548296 ON [CM_WQ1].[dbo].[System_DISC] ([AADTenantID])
CREATE INDEX CMN_missing_index_568418_568417 ON [CM_WQ1].[dbo].[INSTALLED_SOFTWARE_DATA] ([ARPDisplayName00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_281586_281585 ON [CM_WQ1].[dbo].[Update_ComplianceStatus] ([LastStatusCheckTime]) INCLUDE ([CI_ID], [MachineID])
CREATE INDEX CMN_missing_index_548286_548285 ON [CM_WQ1].[dbo].[System_DISC] ([Build01]) INCLUDE ([Obsolete0], [Decommissioned0], [OSBranch01])
CREATE INDEX CMN_missing_index_935_934 ON [CM_WQ1].[dbo].[CI_CIDocuments] ([Document_ID]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_540861_540860 ON [CM_WQ1].[dbo].[INSTALLED_SOFTWARE_DATA] ([ProductName00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_5111_5110 ON [CM_WQ1].[dbo].[Update_DetectionStatus] ([StatusTime]) INCLUDE ([CI_UniqueID], [MachineID])
CREATE INDEX CMN_missing_index_2266_2265 ON [CM_WQ1].[dbo].[Folders] ([ParentContainerNodeID])
CREATE INDEX CMN_missing_index_547750_547749 ON [CM_WQ1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey], [Obsolete0]) INCLUDE ([Name0], [Resource_Domain_OR_Workgr0])
CREATE INDEX CMN_missing_index_20_19 ON [CM_WQ1].[dbo].[PkgServers_L] ([NALPath]) INCLUDE ([Action])
CREATE INDEX CMN_missing_index_548309_548308 ON [CM_WQ1].[dbo].[System_DISC] ([AADTenantID]) INCLUDE ([Client0], [AADDeviceID])
CREATE INDEX CMN_missing_index_972_971 ON [CM_WQ1].[dbo].[Folders] ([Name], [ObjectType], [ParentContainerNodeID], [IsDeleted]) INCLUDE ([ContainerNodeID])
CREATE INDEX CMN_missing_index_974_973 ON [CM_WQ1].[dbo].[Folders] ([Name], [ObjectType], [ParentContainerNodeID], [IsDeleted])
CREATE INDEX CMN_missing_index_548303_548302 ON [CM_WQ1].[dbo].[System_DISC] ([AD_Site_Name0], [Client0], [ManagementAuthority]) INCLUDE ([Obsolete0], [Decommissioned0])
CREATE INDEX CMN_missing_index_548313_548312 ON [CM_WQ1].[dbo].[System_DISC] ([Client0], [Client_Type0]) INCLUDE ([Obsolete0], [Decommissioned0])
CREATE INDEX CMN_missing_index_931_930 ON [CM_WQ1].[dbo].[CI_ConfigurationItems] ([IsTombstoned], [IsExpired],[CIType_ID]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_548301_548300 ON [CM_WQ1].[dbo].[System_DISC] ([Client0], [ManagementAuthority],[AADDeviceID]) INCLUDE ([Obsolete0], [Decommissioned0])
CREATE INDEX CMN_missing_index_561831_561830 ON [CM_WQ1].[dbo].[System_DISC] ([Name0], [Client0], [Obsolete0], [Decommissioned0],[ItemKey])
CREATE INDEX CMN_missing_index_2268_2267 ON [CM_WQ1].[dbo].[FolderMembers] ([IsDeleted]) INCLUDE ([ContainerNodeID])
CREATE INDEX CMN_missing_index_528747_528746 ON [CM_WQ1].[dbo].[User_Group_DISC] ([Usergroup_Name0])
CREATE INDEX CMN_missing_index_548322_548321 ON [CM_WQ1].[dbo].[System_DISC] ([Client0]) INCLUDE ([SMS_Unique_Identifier0], [Obsolete0], [Decommissioned0], [Virtual_Machine_Type0])
CREATE INDEX CMN_missing_index_548317_548316 ON [CM_WQ1].[dbo].[ADDiscoveryStats] ([StartTime]) INCLUDE ([AgentID], [IsFullSync], [DDRCount], [CompleteTime])
CREATE INDEX CMN_missing_index_530427_530426 ON [CM_WQ1].[dbo].[ActiveDirectoryObjectInfo] ([SiteCode],[LastRefreshTime]) INCLUDE ([ObjectGUID])
CREATE INDEX CMN_missing_index_547753_547752 ON [CM_WQ1].[dbo].[CollectionMembers] ([SiteID], [ArchitectureKey]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_1120_1119 ON [CM_WQ1].[dbo].[PkgPrograms_G] ([Description]) INCLUDE ([ProgramID], [PkgID], [ProgramFlags])
CREATE INDEX CMN_missing_index_3478_3477 ON [CM_WQ1].[dbo].[FolderMembers] ([ContainerNodeID]) INCLUDE ([MemberID])
CREATE INDEX CMN_missing_index_548315_548314 ON [CM_WQ1].[dbo].[System_DISC] ([Client0], [Client_Type0]) INCLUDE ([ItemKey], [Obsolete0], [Decommissioned0])
CREATE INDEX CMN_missing_index_280315_280314 ON [CM_WQ1].[dbo].[CI_CIDocuments] ([Document_ID])
CREATE INDEX CMN_missing_index_1632_1631 ON [CM_WQ1].[dbo].[SoftwarePolicy] ([OfferID]) INCLUDE ([PolicyID])
CREATE INDEX CMN_missing_index_8720_8719 ON [CM_WQ1].[dbo].[PkgStatus_L] ([Type]) INCLUDE ([ID], [SiteCode], [PkgServer])
CREATE INDEX CMN_missing_index_27644_27643 ON [CM_WQ1].[dbo].[DeploymentSummary] ([AssignmentID],[Type]) INCLUDE ([SiteNumber], [CollectionID], [OfferID], [SummaryType])
CREATE INDEX CMN_missing_index_929_928 ON [CM_WQ1].[dbo].[CI_UpdateCIs] ([UpdateSource_ID]) INCLUDE ([CI_ID], [DateRevised], [RevisionNumber])
CREATE INDEX CMN_missing_index_3472_3471 ON [CM_WQ1].[dbo].[FolderMembers] ([ContainerNodeID], [IsDeleted]) INCLUDE ([MemberID])
CREATE INDEX CMN_missing_index_5116_5115 ON [CM_WQ1].[dbo].[DBSchema] ([SiteNumber], [ObjectHash])
CREATE INDEX CMN_missing_index_280320_280319 ON [CM_WQ1].[dbo].[CI_ConfigurationItems] ([IsTombstoned]) INCLUDE ([ModelId], [CIVersion], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_280318_280317 ON [CM_WQ1].[dbo].[DeploymentSummary] ([AssignmentID]) INCLUDE ([SiteNumber], [OfferID], [SummaryType])
CREATE INDEX CMN_missing_index_9207_9206 ON [CM_WQ1].[dbo].[PkgServers_L] ([NALPath],[Action])
CREATE INDEX CMN_missing_index_1367_1366 ON [CM_WQ1].[dbo].[Operating_System_DATA] ([Caption00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_14155_14154 ON [CM_WQ1].[dbo].[Network_DATA] ([IPAddress00])
CREATE INDEX CMN_missing_index_3476_3475 ON [CM_WQ1].[dbo].[Folders] ([Name], [ObjectType], [ParentContainerNodeID], [SourceSite],[ContainerNodeID])
CREATE INDEX CMN_missing_index_514840_514839 ON [CM_WQ1].[dbo].[Group_ImmediateSearchBase] ([SearchBaseID]) INCLUDE ([Group_ObjectGUID])
CREATE INDEX CMN_missing_index_3481_3480 ON [CM_WQ1].[dbo].[Folders] ([ParentContainerNodeID]) INCLUDE ([ContainerNodeID], [Name])
CREATE INDEX CMN_missing_index_548288_548287 ON [CM_WQ1].[dbo].[DeploymentSummary] ([Type]) INCLUDE ([SiteNumber], [CollectionID], [OfferID], [ModelID], [AssignmentID], [SummaryType])
CREATE INDEX CMN_missing_index_548305_548304 ON [CM_WQ1].[dbo].[CI_ConfigurationItems] ([IsUserDefined]) INCLUDE ([CI_ID])
