CREATE INDEX CMN_missing_index_53_52 ON [CM_SQ1].[dbo].[AttributeMap] ([GroupKey], [IsKey])
CREATE INDEX CMN_missing_index_55_54 ON [CM_SQ1].[dbo].[AttributeMap] ([IsKey]) INCLUDE ([GroupKey])
CREATE INDEX CMN_missing_index_92_91 ON [CM_SQ1].[dbo].[DeploymentSummary] ([OfferID])
CREATE INDEX CMN_missing_index_2752_2751 ON [CM_SQ1].[dbo].[CI_ConfigurationItems] ([CIType_ID], [IsTombstoned]) INCLUDE ([ModelId])
CREATE INDEX CMN_missing_index_2754_2753 ON [CM_SQ1].[dbo].[CI_ConfigurationItems] ([IsTombstoned],[CIType_ID]) INCLUDE ([ModelId])
CREATE INDEX CMN_missing_index_111_110 ON [CM_SQ1].[dbo].[RBAC_InstancePermissions] ([ObjectTypeID]) INCLUDE ([AdminID], [ObjectKey], [GrantedOperations])
CREATE INDEX CMN_missing_index_1074_1073 ON [CM_SQ1].[dbo].[Update_ComplianceStatus] ([EnforcementSource],[LastEnforcementMessageID], [LastEnforcementMessageTime]) INCLUDE ([CI_ID], [MachineID])
CREATE INDEX CMN_missing_index_1943_1942 ON [DBATools].[Paramain].[ObjectGroup] ([SPID]) INCLUDE ([ObjectGroupID])
CREATE INDEX CMN_missing_index_189_188 ON [CM_SQ1].[dbo].[CI_ConfigurationItems] ([IsHidden], [IsTombstoned],[CIType_ID]) INCLUDE ([CI_ID], [CI_UniqueID], [ModelId], [CIVersion], [DateCreated], [DateLastModified], [LastModifiedBy], [CreatedBy], [PermittedUses], [IsBundle], [IsUserDefined], [IsEnabled], [IsExpired], [IsLatest], [SourceSite], [ApplicabilityCondition], [ConfigurationFlags], [IsUserCI], [SEDOComponentID])
CREATE INDEX CMN_missing_index_3200_3199 ON [CM_SQ1].[dbo].[Update_ComplianceStatus] ([Status]) INCLUDE ([CI_ID], [MachineID], [EnforcementSource], [LastEnforcementMessageID])
CREATE INDEX CMN_missing_index_184_183 ON [CM_SQ1].[dbo].[System_DISC] ([ManagementAuthority]) INCLUDE ([SMS_Unique_Identifier0])
CREATE INDEX CMN_missing_index_192_191 ON [CM_SQ1].[dbo].[CI_ConfigurationItems] ([CIType_ID]) INCLUDE ([CI_ID], [ModelId], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_10_9 ON [CM_SQ1].[dbo].[BGB_ResStatus] ([ServerID]) INCLUDE ([ResourceID], [OnlineStatus])
CREATE INDEX CMN_missing_index_8_7 ON [CM_SQ1].[dbo].[CI_ConfigurationItems] ([IsTombstoned], [IsExpired], [SourceSite],[CIType_ID]) INCLUDE ([CI_ID], [DateCreated], [DateLastModified])
CREATE INDEX CMN_missing_index_19_18 ON [CM_SQ1].[dbo].[DepPolicyAssignment] ([DepPADBID]) INCLUDE ([PADBID], [IsTombstoned])
CREATE INDEX CMN_missing_index_24_23 ON [CM_SQ1].[dbo].[PolicyAssignment] ([PolicyAssignmentID])
CREATE INDEX CMN_missing_index_2933_2932 ON [CM_SQ1].[dbo].[CI_ConfigurationItems] ([IsTombstoned]) INCLUDE ([ConfigurationFlags])
CREATE INDEX CMN_missing_index_70_69 ON [CM_SQ1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([Client0], [Client_Type0], [Obsolete0])
CREATE INDEX CMN_missing_index_74_73 ON [CM_SQ1].[dbo].[DeploymentSummary] ([AssignmentID]) INCLUDE ([SummarizationTime])
CREATE INDEX CMN_missing_index_44_43 ON [CM_SQ1].[dbo].[ResOfferCollMap] ([OfferID]) INCLUDE ([MachineID], [CollectionID])
CREATE INDEX CMN_missing_index_12_11 ON [CM_SQ1].[dbo].[ContentDPMap] ([ServerName], [SiteCode]) INCLUDE ([ContentID], [ServerPath], [AccessType], [Version], [URL], [URLSubPath], [URLProtocol], [State], [SigURL], [SigURLSubPath])
CREATE INDEX CMN_missing_index_1965_1964 ON [DBATools].[Paramain].[CommandLog] ([DatabaseName], [SchemaName], [ObjectName], [ObjectType], [EndTime]) INCLUDE ([conversation_handle])
CREATE INDEX CMN_missing_index_16_15 ON [CM_SQ1].[dbo].[ClientDeploymentState] ([BaselineCookie]) INCLUDE ([RecordID], [SMSID], [InstalledLangs])
CREATE INDEX CMN_missing_index_533_532 ON [CM_SQ1].[dbo].[CI_ConfigurationItems] ([IsTombstoned]) INCLUDE ([CI_ID], [CIType_ID], [IsExpired], [IsLatest], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_80_79 ON [ReportServer].[dbo].[Catalog] ([Type]) INCLUDE ([ParentID])
CREATE INDEX CMN_missing_index_2817_2816 ON [CM_SQ1].[dbo].[CI_CurrentComplianceStatus] ([UserID]) INCLUDE ([ModelID], [ItemKey], [CIVersion], [IsApplicable], [IsDetected], [IsEnforced], [ComplianceState], [MaxNoncomplianceCriticality])
CREATE INDEX CMN_missing_index_2416_2415 ON [CM_SQ1].[dbo].[LU_SoftwareList] ([SourceSite],[LastUpdated])
CREATE INDEX CMN_missing_index_14_13 ON [CM_SQ1].[dbo].[ContentDPMap] ([SiteCode]) INCLUDE ([ContentID], [ServerName], [ServerPath], [AccessType], [Version], [URL], [URLSubPath], [URLProtocol], [State], [SigURL], [SigURLSubPath])
CREATE INDEX CMN_missing_index_76_75 ON [CM_SQ1].[dbo].[DeploymentSummary] ([OfferID]) INCLUDE ([SummarizationTime])
CREATE INDEX CMN_missing_index_2422_2421 ON [CM_SQ1].[dbo].[LU_SoftwareCode] ([SoftwareCode]) INCLUDE ([SoftwareID])
CREATE INDEX CMN_missing_index_163_162 ON [CM_SQ1].[dbo].[DeploymentSummary] ([OfferID],[Type]) INCLUDE ([NumberInstalled], [NumberInProgress], [NumberUnknown], [NumberErrors], [NumberReqsNotMet], [SummarizationTime])
CREATE INDEX CMN_missing_index_82_81 ON [ReportServer].[dbo].[Catalog] ([Type]) INCLUDE ([ItemID], [Path], [ParentID], [Description], [Hidden], [CreationDate])
CREATE INDEX CMN_missing_index_107_106 ON [CM_SQ1].[dbo].[CI_CIDocuments] ([Document_ID]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_29_28 ON [CM_SQ1].[dbo].[PolicyAssignment] ([IsTombstoned]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_33_32 ON [CM_SQ1].[dbo].[PolicyAssignment] ([IsTombstoned]) INCLUDE ([PADBID], [PolicyAssignmentID])
CREATE INDEX CMN_missing_index_21_20 ON [CM_SQ1].[dbo].[DepPolicyAssignment] ([IsTombstoned]) INCLUDE ([PADBID], [DepPADBID])
CREATE INDEX CMN_missing_index_165_164 ON [CM_SQ1].[dbo].[CI_ConfigurationItemsOptionalRelations] ([RelationType]) INCLUDE ([FromCI_ID], [ToCI_ID], [IsVersionSpecific])
CREATE INDEX CMN_missing_index_2418_2417 ON [CM_SQ1].[dbo].[LU_SoftwareHash] ([SourceSite],[LastUpdated])
CREATE INDEX CMN_missing_index_498_497 ON [CM_SQ1].[dbo].[SCCM_Audit] ([ChangeTime]) INCLUDE ([ID])
CREATE INDEX CMN_missing_index_2692_2691 ON [CM_SQ1].[dbo].[StatusMessages] ([DeleteTime]) INCLUDE ([RecordID])
CREATE INDEX CMN_missing_index_37_36 ON [CM_SQ1].[dbo].[PolicyAssignment] ([PolicyAssignmentID]) INCLUDE ([PADBID])
CREATE INDEX CMN_missing_index_197_196 ON [CM_SQ1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([Netbios_Name0], [Is_Virtual_Machine0], [Is_MachineChanges_Persisted0], [Is_Assigned_To_User0], [Virtual_Machine_Host_Name0])
CREATE INDEX CMN_missing_index_90_89 ON [CM_SQ1].[dbo].[BGB_ResStatus] ([ServerID]) INCLUDE ([OnlineStatus])
CREATE INDEX CMN_missing_index_2875_2874 ON [CM_SQ1].[dbo].[INSTALLED_SOFTWARE_DATA] ([ProductName00])
CREATE INDEX CMN_missing_index_216_215 ON [CM_SQ1].[dbo].[CI_ConfigurationItemsOptionalRelations] ([RelationType], [IsVersionSpecific]) INCLUDE ([FromCI_ID], [ToCI_ID])
CREATE INDEX CMN_missing_index_31_30 ON [CM_SQ1].[dbo].[ResPolicyMap] ([IsTombstoned]) INCLUDE ([MachineID], [PADBID])
CREATE INDEX CMN_missing_index_727_726 ON [CM_SQ1].[dbo].[CollectionNotifications] ([Group_ObjectGUID],[RecordID]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_1154_1153 ON [CM_SQ1].[dbo].[Update_ComplianceStatus] ([MachineID]) INCLUDE ([CI_ID], [Status], [LastStatusCheckTime], [LastEnforcementMessageID], [rowversion])
CREATE INDEX CMN_missing_index_2717_2716 ON [CM_SQ1].[dbo].[INSTALLED_SOFTWARE_DATA] ([ProductName00]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_507_506 ON [CM_SQ1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey], [Netbios_Name0]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Resource_Domain_OR_Workgr0], [Client0])
CREATE INDEX CMN_missing_index_105_104 ON [CM_SQ1].[dbo].[CI_ConfigurationItems] ([IsTombstoned], [IsExpired],[CIType_ID]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_527_526 ON [CM_SQ1].[dbo].[CI_CIDocuments] ([Document_ID])
CREATE INDEX CMN_missing_index_103_102 ON [CM_SQ1].[dbo].[CI_UpdateCIs] ([UpdateSource_ID]) INCLUDE ([CI_ID], [DateRevised], [RevisionNumber])
CREATE INDEX CMN_missing_index_278_277 ON [CM_SQ1].[dbo].[Update_DetectionStatus] ([StatusTime]) INCLUDE ([CI_UniqueID], [MachineID])
CREATE INDEX CMN_missing_index_2789_2788 ON [CM_SQ1].[dbo].[CI_CurrentComplianceStatus] ([UserID]) INCLUDE ([CI_CurrentComplianceStatusID], [ModelID], [ItemKey], [CIVersion], [IsEnforced], [ComplianceState], [MaxNoncomplianceCriticality])
CREATE INDEX CMN_missing_index_724_723 ON [CM_SQ1].[dbo].[CollectionNotifications] ([TableName],[RecordID], [MachineID])
CREATE INDEX CMN_missing_index_4_3 ON [CM_SQ1].[dbo].[PkgStatus_L] ([Type], [PkgServer]) INCLUDE ([ID])
CREATE INDEX CMN_missing_index_1568_1567 ON [CM_SQ1].[dbo].[CI_ConfigurationItems] ([IsTombstoned]) INCLUDE ([CI_ID], [ModelId], [CIType_ID])
CREATE INDEX CMN_missing_index_6_5 ON [CM_SQ1].[dbo].[PkgStatus_L] ([Type]) INCLUDE ([ID], [PkgServer])
CREATE INDEX CMN_missing_index_955_954 ON [CM_SQ1].[dbo].[ResOfferCollMap] ([OfferID]) INCLUDE ([MachineID])
CREATE INDEX CMN_missing_index_1920_1919 ON [CM_SQ1].[dbo].[Update_ComplianceStatus] ([MachineID],[LastStatusCheckTime], [LastEnforcementMessageTime]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_524_523 ON [CM_SQ1].[dbo].[CI_ConfigurationItems] ([IsTombstoned], [IsExpired], [SourceSite],[CIType_ID]) INCLUDE ([CI_ID], [DateCreated], [DateLastModified], [rowversion])
CREATE INDEX CMN_missing_index_496_495 ON [CM_SQ1].[dbo].[SEDO_LockRequests] ([RequestTime]) INCLUDE ([ID])
CREATE INDEX CMN_missing_index_2906_2905 ON [CM_SQ1].[dbo].[CI_ConfigurationItems] ([IsHidden], [IsTombstoned],[CIType_ID]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_78_77 ON [ReportServer].[dbo].[ExecutionLogStorage] ([InstanceName], [ReportAction]) INCLUDE ([TimeStart])
CREATE INDEX CMN_missing_index_331_330 ON [CM_SQ1].[dbo].[System_DISC] ([Client0], [Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Operating_System_Name_and0], [Resource_Domain_OR_Workgr0])
CREATE INDEX CMN_missing_index_988_987 ON [CM_SQ1].[dbo].[System_DATA] ([Name0])
CREATE INDEX CMN_missing_index_333_332 ON [CM_SQ1].[dbo].[System_DISC] ([Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Netbios_Name0], [Name0], [Resource_Domain_OR_Workgr0], [Client0])
CREATE INDEX CMN_missing_index_1026_1025 ON [CM_SQ1].[dbo].[System_DISC] ([Operating_System_Name_and0], [Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Resource_Domain_OR_Workgr0], [Client0])
CREATE INDEX CMN_missing_index_281_280 ON [CM_SQ1].[dbo].[DBSchema] ([SiteNumber], [ObjectHash])
CREATE INDEX CMN_missing_index_35_34 ON [CM_SQ1].[dbo].[DepPolicyAssignment] ([PolicyAssignmentID]) INCLUDE ([PADBID], [DepPADBID])
CREATE INDEX CMN_missing_index_2_1 ON [CM_SQ1].[dbo].[BGB_ResStatus] ([ServerID],[OnlineStatus]) INCLUDE ([ResourceID])
CREATE INDEX CMN_missing_index_510_509 ON [CM_SQ1].[dbo].[System_DISC] ([Resource_Domain_OR_Workgr0], [Decommissioned0],[ItemKey]) INCLUDE ([DiscArchKey], [SMS_Unique_Identifier0], [Name0], [Client0])
CREATE INDEX CMN_missing_index_482_481 ON [CM_SQ1].[dbo].[DepPolicyAssignment] ([DepPADBID], [IsTombstoned])
CREATE INDEX CMN_missing_index_484_483 ON [CM_SQ1].[dbo].[DepPolicyAssignment] ([IsTombstoned]) INCLUDE ([DepPADBID])
CREATE INDEX CMN_missing_index_2929_2928 ON [CM_SQ1].[dbo].[CI_ConfigurationItems] ([IsTombstoned], [IsExpired]) INCLUDE ([CI_ID], [MinRequiredVersion])
CREATE INDEX CMN_missing_index_1789_1788 ON [CM_SQ1].[dbo].[ResPolicyMap] ([TargetSourceID], [IsTombstoned]) INCLUDE ([MachineID], [PADBID])
CREATE INDEX CMN_missing_index_3327_3326 ON [CM_SQ1].[dbo].[CI_CurrentComplianceStatus] ([ItemKey],[LastComplianceMessageTime], [LastEnforcementMessageTime], [LastLaunchStateMessageTime]) INCLUDE ([CI_CurrentComplianceStatusID])
CREATE INDEX CMN_missing_index_2909_2908 ON [CM_SQ1].[dbo].[CI_ConfigurationItems] ([IsUserDefined]) INCLUDE ([CI_ID])
CREATE INDEX CMN_missing_index_2599_2598 ON [DBATools].[Paramain].[ObjectGroup] ([SPID]) INCLUDE ([ObjectGroupID], [DatabaseName], [SchemaName], [ObjectName], [ObjectType])
CREATE INDEX CMN_missing_index_1393_1392 ON [CM_SQ1].[dbo].[System_DISC] ([Name0], [Decommissioned0],[ItemKey])
CREATE INDEX CMN_missing_index_3648_3647 ON [CM_SQ1].[dbo].[ResOfferCollMap] ([OfferID])
CREATE INDEX CMN_missing_index_26_25 ON [CM_SQ1].[dbo].[System_DISC] ([Client_Type0],[AgentEdition0]) INCLUDE ([ItemKey])
CREATE INDEX CMN_missing_index_734_733 ON [CM_SQ1].[dbo].[BGB_ResStatus] ([OnlineStatus], [ServerID]) INCLUDE ([ResourceID])
CREATE INDEX CMN_missing_index_2921_2920 ON [CM_SQ1].[dbo].[ClientKeyData] ([AADTenantID]) INCLUDE ([AADDeviceID])
CREATE INDEX CMN_missing_index_530_529 ON [CM_SQ1].[dbo].[DeploymentSummary] ([AssignmentID]) INCLUDE ([SiteNumber], [OfferID], [SummaryType])
CREATE INDEX CMN_missing_index_2185_2184 ON [CM_SQ1].[dbo].[CH_ClientSummaryHistory] ([CollectionID],[Date])
