##All 1E Scripts Copied from MEMCM

#Nomad Cache Cleaner
param (
[string]$pkgid,
[int]$pkgver
)

if (Test-Path -Path HKLM:\SOFTWARE\1e\NomadBranch -ErrorAction SilentlyContinue) {
    $InstallDir = (Get-ItemProperty -Path HKLM:\SOFTWARE\1E\NomadBranch -Name InstallationDirectory).InstallationDirectory
    & "$InstallDir\CacheCleaner.exe" "-DeletePkg=$pkgid" "-PkgVer=$pkgver"
} else {
    Write-Output 'Nomad not installed.'
}

#Relicense
Start-Process -FilePath "C:\Program Files\1E\NomadBranch\nomadbranch.exe" -ArgumentList "-relicense=HUMNOM6-64RB-1ILL-9EBL-7UVF"

#Remove QA generated LZ files
$LocalCachePath = [string](Get-ItemProperty -Path Registry::HKEY_LOCAL_MACHINE\SOFTWARE\1E\NomadBranch -Name LocalCachePath -ErrorAction Ignore).LocalCachePath

#Time
function Get-TimeStamp {
    return "[{0:MM/dd/yy} {0:HH:mm:ss}]" -f (Get-Date)
}


#Loop through the .LsZ files and return any that were generated by a QA DP.
$AllLSZ = Get-ChildItem -Path $LocalCachePath -Filter *.LsZ 
ForEach ($File in $AllLSZ) {
    If (Get-Content -Path $file.FullName | Select-String 'Generated by "LOUAPPWQ') {
        $(Get-TimeStamp), $File.BaseName | Out-File -FilePath "C:\temp\RemovedLsZfiles.txt" -Append
        $PkgInfo = $File.Basename -split '_'
        $PkgID = $PkgInfo[0]
        $Arg_PkgID = "-DeletePkg=$PkgID"
        $PkgVer = $PkgInfo[1]
        $Arg_PkgVer = "-PkgVer=$PkgVer"
        $startProcessSplat = @{
            PassThru     = $true
            FilePath     = "$env:ProgramFiles\1E\NomadBranch\CacheCleaner.exe"
            ArgumentList = $Arg_PkgID, $Arg_PkgVer
            WindowStyle  = 'Hidden'
            Wait         = $true
        }
        Start-Process @startProcessSplat
    }
}

Exit $LASTEXITCODE

#Restart Nomad service
Restart-Service NomadBranch -Force

#Pre-cache trigger
& 'C:\Program Files\1E\Client\Extensibility\NomadBranch\NomadBranch.exe' -PreCache