#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 5/21/2015 3:48 PM
# Generated By: TDR2928
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$frmSpinningWheel = New-Object System.Windows.Forms.Form
$pictureBoxSpinningWheel = New-Object System.Windows.Forms.PictureBox
$lblSpinningWheelFormLoadingText = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 119
$System_Drawing_Size.Width = 224
$frmSpinningWheel.ClientSize = $System_Drawing_Size
$frmSpinningWheel.DataBindings.DefaultDataSourceUpdateMode = 0
$frmSpinningWheel.Name = "frmSpinningWheel"
$frmSpinningWheel.Text = "Loading"


$pictureBoxSpinningWheel.DataBindings.DefaultDataSourceUpdateMode = 0
#$env:SMS_ADMIN_UI_PATH
$pictureBoxSpinningWheel.Image = [System.Drawing.Image]::FromFile('c:\data\sccm\scripts\spinning-wheel.gif')

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 84
$System_Drawing_Point.Y = 40
$pictureBoxSpinningWheel.Location = $System_Drawing_Point
$pictureBoxSpinningWheel.Name = "pictureBoxSpinningWheel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 60
$System_Drawing_Size.Width = 60
$pictureBoxSpinningWheel.Size = $System_Drawing_Size
$pictureBoxSpinningWheel.TabIndex = 1
$pictureBoxSpinningWheel.TabStop = $False

$frmSpinningWheel.Controls.Add($pictureBoxSpinningWheel)

$lblSpinningWheelFormLoadingText.DataBindings.DefaultDataSourceUpdateMode = 0
$lblSpinningWheelFormLoadingText.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",15.75,0,3,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 9
$System_Drawing_Point.Y = 9
$lblSpinningWheelFormLoadingText.Location = $System_Drawing_Point
$lblSpinningWheelFormLoadingText.Name = "lblSpinningWheelFormLoadingText"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 43
$System_Drawing_Size.Width = 215
$lblSpinningWheelFormLoadingText.Size = $System_Drawing_Size
$lblSpinningWheelFormLoadingText.TabIndex = 0
$lblSpinningWheelFormLoadingText.Text = "Loading, please wait"

$frmSpinningWheel.Controls.Add($lblSpinningWheelFormLoadingText)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $frmSpinningWheel.WindowState
#Init the OnLoad event to correct the initial state of the form
$frmSpinningWheel.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$frmSpinningWheel.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
